#!/usr/bin/env python3
"""Turn ``contracts/theme.json`` into the web's actual design tokens.

This generator never reads Swift. That is the point of splitting it from ``gen_theme.py``:
``theme.json`` is the one place the four Swift-declaration shapes get parsed, and everything
downstream of it — this script, and eventually a web build — only ever reads plain, already
-validated JSON. A bug in a CSS custom-property name can therefore never be confused with a bug
in the Swift parser; they are two different failure domains with two different scripts.

It emits two files into ``web/src/generated/``, both stamped "GENERATED — DO NOT EDIT" so nobody
hand-patches a color and has it silently overwritten (or worse, not overwritten, and now the
running site disagrees with the source of truth):

* ``tokens.css`` — CSS custom properties on ``:root``, with the whole palette redefined once for
  ``prefers-color-scheme: dark`` and once more under ``:root[data-theme="dark"]`` for an explicit
  in-app toggle that overrides the OS setting. Three things a hand-written stylesheet reliably
  gets wrong, and this generator cannot: the card shadow becomes the literal keyword ``none`` in
  dark mode (SwiftUI sets `Color.clear`, so merely dimming the opacity would be a different,
  wrong effect — dark mode separates surfaces by lightness step instead); an accent's soft-tint
  alpha is looked up per accent *and* per mode (amber alone differs from the other eight in light
  mode); and the chart and monogram ramps stay in two separate, never-merged namespaces, so a
  team badge can never end up sharing a color with a chart series in the same row.
* ``tokens.ts`` — the same values as typed, frozen JS objects/arrays, for the call sites (mostly
  hand-rolled SVG) that need a literal color string rather than something the browser resolves
  from a custom property, because an SVG ``fill`` cannot always be handed ``var(--hw-chart-0)``
  and be sure of which appearance it will render in for a static export or a canvas readback.

Usage: ``python3 contracts/tools/gen_web_tokens.py`` writes both files straight into
``web/src/generated/`` so the two stay a matched pair from a single invocation, the way
``sync_contracts.sh`` expects to run it. ``--out DIR`` writes them into ``DIR`` instead (by
basename, not the nested path) — ``scripts/check_contracts.py`` check (i) uses this to render a
fresh copy into a scratch directory and diff it against the committed one, the multi-file
equivalent of comparing a single generator's stdout the way checks (a) already does; this
generator writes two related files from one JSON read, so redirecting stdout to one filename
would not cover the other.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
THEME_JSON = ROOT / "contracts" / "theme.json"
DEFAULT_OUT_DIR = ROOT / "web" / "src" / "generated"

BANNER_CSS = "/* GENERATED by contracts/tools/gen_web_tokens.py — DO NOT EDIT. */"
BANNER_TS = "// GENERATED by contracts/tools/gen_web_tokens.py — DO NOT EDIT."

#: Declaration order for the values `theme.json` (sorted-key JSON, for diffable regeneration)
#: does not preserve. Each tuple mirrors the order the *Swift* source declares the same names in,
#: so a person reading the emitted CSS top-to-bottom sees the same order they would in
#: `Theme.swift` — order that has no runtime meaning for a CSS custom property, but a great deal
#: of meaning for a person scanning a diff.
PALETTE_ORDER = (
    "background", "surface", "surfaceRaised", "surfaceSunken", "separator",
    "textPrimary", "textSecondary", "textTertiary",
    "positive", "negative", "neutral", "warning", "selection",
    "track", "skeleton", "skeletonHighlight",
)
SPACING_ORDER = ("hairline", "xxs", "xs", "sm", "md", "lg", "xl", "xxl")
RADIUS_ORDER = ("chip", "control", "card", "sheet", "pill")
#: `AccentName`'s declaration order in `ios/NBAStats/Core/DashboardLayout.swift`.
ACCENT_ORDER = ("orange", "indigo", "teal", "red", "amber", "green", "blue", "purple", "graphite")
BROADSHEET_COLOR_ORDER = (
    "background", "text", "textMuted", "rule", "band", "accentAbove", "accentBelow",
)
BROADSHEET_METRIC_ORDER = ("bandHeight", "dotSize", "tickWidth", "tickHeight", "kickerTracking")
#: `HardwoodTextStyle`'s declaration order in `ios/NBAStats/DesignSystem/Typography.swift`.
TEXT_STYLE_ORDER = (
    "displayValue", "statValue", "statLabel", "tableHeader",
    "tableCell", "caption", "sectionTitle", "widgetTitle",
)
SIZE_ORDER = ("small", "medium", "large")

#: `displayValue` and `statValue` are the two styles whose whole job is to *be* a number; the
#: design's own worked example (WEB_DESIGN.md §8.2) shortens them to `--hw-font-display-*` and
#: (by the same rule) `--hw-font-stat-*` rather than the longer `display-value` / `stat-value` —
#: the CSS variable names the number-styled text components are written against. Every other
#: style kebab-cases as-is.
_STRIP_VALUE_SUFFIX = re.compile(r"Value$")


def _kebab(name: str) -> str:
    """``surfaceRaised`` -> ``surface-raised``. Plain camelCase-to-kebab; no other magic."""
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def _font_slug(style_name: str) -> str:
    return _kebab(_STRIP_VALUE_SUFFIX.sub("", style_name))


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    value = hex_color.lstrip("#")
    return int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16)


def _rgba(hex_color: str, alpha: float) -> str:
    r, g, b = _hex_to_rgb(hex_color)
    # Match Python's own float repr for the common alphas (0.12, 0.14, 0.2, 0.95, ...) rather
    # than re-adding trailing zeros a CSS author would never type by hand.
    alpha_text = f"{alpha:g}"
    return f"rgba({r},{g},{b},{alpha_text})"


#: The two candidates for label text sitting *on* an accent fill. Near-black rather than pure
#: black so it matches the dark palette's own `background` step instead of punching a hole.
_ON_ACCENT_CANDIDATES = ("#0C0E12", "#FFFFFF")


def _relative_luminance(hex_color: str) -> float:
    """WCAG 2.1 relative luminance."""

    def channel(raw: int) -> float:
        c = raw / 255
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = _hex_to_rgb(hex_color)
    return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)


def _contrast(a: str, b: str) -> float:
    la, lb = _relative_luminance(a), _relative_luminance(b)
    lighter, darker = max(la, lb), min(la, lb)
    return (lighter + 0.05) / (darker + 0.05)


def _on_accent(hex_color: str) -> str:
    """The label colour to put on top of ``hex_color``, whichever of near-black and white has
    more contrast against it.

    This exists because five components hard-coded ``color: white`` on
    ``background: var(--hw-accent-orange)`` — fine at 5.18:1 in light mode, and 2.26:1 in dark,
    where the accent lightens to ``#FB923C``. That failed AA on the sign-in button, the
    editor's primary toolbar button, every preset card's "Use this", and the *selected* tab on
    /fantasy and on a box score. `stylelint`'s hex/rgba ban does not catch the bare keyword
    ``white``, which is why nothing reported it.
    """
    return max(_ON_ACCENT_CANDIDATES, key=lambda candidate: _contrast(hex_color, candidate))


def _px(value: float) -> str:
    return f"{value:g}px"


def _num(value: float) -> str:
    return f"{value:g}"


def load_theme() -> dict[str, Any]:
    if not THEME_JSON.is_file():
        print(f"{THEME_JSON}: does not exist; run gen_theme.py first", file=sys.stderr)
        raise SystemExit(1)
    return json.loads(THEME_JSON.read_text(encoding="utf-8"))


# --------------------------------------------------------------------------- CSS emission


def _mode_declarations(theme: dict[str, Any], mode: str) -> list[str]:
    """Every custom property whose value differs between ``light`` and ``dark``."""
    lines: list[str] = []
    palette = theme["palette"]
    for key in PALETTE_ORDER:
        entry = palette[key]
        value = entry[mode]
        alpha = entry.get(f"{mode}Alpha", 1)
        if alpha != 1:
            value = _rgba(value, alpha)
        lines.append(f"  --hw-{_kebab(key)}:{value};")

    for index, entry in enumerate(theme["chartSeries"]):
        lines.append(f"  --hw-chart-{index}:{entry[mode]};")
    for index, entry in enumerate(theme["monogramPalette"]):
        lines.append(f"  --hw-mono-{index}:{entry[mode]};")

    accents = theme["accents"]
    for name in ACCENT_ORDER:
        entry = accents[name]
        soft_alpha = entry[f"soft{mode.capitalize()}Alpha"]
        lines.append(f"  --hw-accent-{name}:{entry[mode]};")
        lines.append(f"  --hw-accent-{name}-soft:{_rgba(entry[mode], soft_alpha)};")
        lines.append(f"  --hw-on-accent-{name}:{_on_accent(entry[mode])};")

    broadsheet = theme["broadsheet"]
    for key in BROADSHEET_COLOR_ORDER:
        lines.append(f"  --hw-bs-{_kebab(key)}:{broadsheet[key][mode]};")

    shadow = theme["shadow"]
    if mode == "light":
        card, raised, drag = shadow["card"], shadow["raised"], shadow["drag"]
        lines.append(f"  --hw-card-shadow:0 {card['y']}px {card['blur']}px {card['color']};")
        lines.append(
            f"  --hw-card-shadow-raised:0 {raised['y']}px {raised['blur']}px {raised['color']};"
        )
        lines.append(f"  --hw-shadow-drag:0 {drag['y']}px {drag['blur']}px {drag['color']};")
    else:
        # `shadow.dark` is the literal keyword "none": SwiftUI sets `Color.clear` for the raised
        # card shadow in dark mode, and dark mode separates surfaces by lightness instead of a
        # shadow (Theme.swift's own comment: "a black shadow on a near-black page is invisible").
        # The drag shadow is the one shadow dark mode keeps (WEB_DESIGN.md §7.5) because it is a
        # transient, high-contrast affordance during a drag, not ambient card elevation.
        drag = shadow["drag"]
        lines.append(f"  --hw-card-shadow:{shadow['dark']};")
        lines.append(f"  --hw-card-shadow-raised:{shadow['dark']};")
        lines.append(f"  --hw-shadow-drag:0 {drag['y']}px {drag['blur']}px {drag['color']};")

    return lines


def _mode_independent_declarations(theme: dict[str, Any]) -> list[str]:
    """Custom properties with exactly one value: spacing, radius, broadsheet metrics, type."""
    lines: list[str] = []
    spacing = theme["spacing"]
    for key in SPACING_ORDER:
        lines.append(f"  --hw-space-{key}:{_px(spacing[key])};")
    radius = theme["radius"]
    for key in RADIUS_ORDER:
        lines.append(f"  --hw-radius-{key}:{_px(radius[key])};")

    metrics = theme["broadsheet"]["metrics"]
    for key in BROADSHEET_METRIC_ORDER:
        value = metrics[key]
        # `kickerTracking` is a `CGFloat` letter-spacing offset (points), like the others; only
        # its name doesn't end in the usual Size/Width/Height.
        lines.append(f"  --hw-bs-{_kebab(key)}:{_px(value)};")

    text_styles = theme["textStyles"]
    for name in TEXT_STYLE_ORDER:
        style = text_styles[name]
        slug = _font_slug(name)
        lines.append(f"  --hw-font-{slug}-size:{_px(style['px'])};")
        lines.append(f"  --hw-font-{slug}-weight:{style['weight']};")
        lines.append(f"  --hw-font-{slug}-tracking:{_px(style['tracking'])};")
        numeric = "tabular-nums" if style["numeric"] else "normal"
        lines.append(f"  --hw-font-{slug}-numeric:{numeric};")

    return lines


def render_css(theme: dict[str, Any]) -> str:
    light = _mode_declarations(theme, "light")
    dark = _mode_declarations(theme, "dark")
    shared = _mode_independent_declarations(theme)
    default_accent = [
        "  --hw-accent:var(--hw-accent-orange);",
        "  --hw-accent-soft:var(--hw-accent-orange-soft);",
        "  --hw-on-accent:var(--hw-on-accent-orange);",
    ]

    parts = [
        BANNER_CSS,
        ":root{",
        *light,
        *shared,
        *default_accent,
        "}",
        "@media (prefers-color-scheme: dark){",
        '  :root:not([data-theme="light"]){',
        *(f"  {line}" for line in dark),
        "  }",
        "}",
        ':root[data-theme="dark"]{',
        *dark,
        "}",
        "",
    ]
    return "\n".join(parts)


# --------------------------------------------------------------------------- TS emission


def _ts_string(value: str) -> str:
    return json.dumps(value)


def render_ts(theme: dict[str, Any]) -> str:
    lines: list[str] = [BANNER_TS, ""]

    lines.append("export const CHART_SERIES_LIGHT = [")
    for entry in theme["chartSeries"]:
        lines.append(f"  {_ts_string(entry['light'])},")
    lines.append("] as const;")
    lines.append("")
    lines.append("export const CHART_SERIES_DARK = [")
    for entry in theme["chartSeries"]:
        lines.append(f"  {_ts_string(entry['dark'])},")
    lines.append("] as const;")
    lines.append("")

    lines.append("export interface MonogramSwatch {")
    lines.append("  readonly light: string;")
    lines.append("  readonly dark: string;")
    lines.append("}")
    lines.append("")
    lines.append("export const MONOGRAM_PALETTE: readonly MonogramSwatch[] = [")
    for entry in theme["monogramPalette"]:
        light, dark = _ts_string(entry["light"]), _ts_string(entry["dark"])
        lines.append(f"  {{ light: {light}, dark: {dark} }},")
    lines.append("];")
    lines.append("")

    lines.append("export interface AccentTokens {")
    lines.append("  readonly light: string;")
    lines.append("  readonly dark: string;")
    lines.append("  readonly softLightAlpha: number;")
    lines.append("  readonly softDarkAlpha: number;")
    lines.append("}")
    lines.append("")
    accent_type = " | ".join(_ts_string(name) for name in ACCENT_ORDER)
    lines.append(f"export type AccentName = {accent_type};")
    lines.append("")
    lines.append("export const ACCENTS: Readonly<Record<AccentName, AccentTokens>> = {")
    for name in ACCENT_ORDER:
        entry = theme["accents"][name]
        light, dark = _ts_string(entry["light"]), _ts_string(entry["dark"])
        soft_light, soft_dark = entry["softLightAlpha"], entry["softDarkAlpha"]
        lines.append(
            f"  {name}: {{ light: {light}, dark: {dark}, "
            f"softLightAlpha: {soft_light}, softDarkAlpha: {soft_dark} }},"
        )
    lines.append("};")
    lines.append("")

    spacing = theme["spacing"]
    lines.append("export const SPACING = {")
    for key in SPACING_ORDER:
        lines.append(f"  {key}: {_num(spacing[key])},")
    lines.append("} as const;")
    lines.append("")

    radius = theme["radius"]
    lines.append("export const RADIUS = {")
    for key in RADIUS_ORDER:
        lines.append(f"  {key}: {_num(radius[key])},")
    lines.append("} as const;")
    lines.append("")

    lines.append("export interface TextStyleTokens {")
    lines.append("  readonly px: number;")
    lines.append("  readonly weight: number;")
    lines.append("  readonly tracking: number;")
    lines.append("  readonly numeric: boolean;")
    lines.append("  readonly color: string;")
    lines.append("}")
    lines.append("")
    style_type = " | ".join(_ts_string(name) for name in TEXT_STYLE_ORDER)
    lines.append(f"export type HardwoodTextStyleName = {style_type};")
    lines.append("")
    lines.append(
        "export const TEXT_STYLES: "
        "Readonly<Record<HardwoodTextStyleName, TextStyleTokens>> = {"
    )
    for name in TEXT_STYLE_ORDER:
        style = theme["textStyles"][name]
        lines.append(
            f"  {name}: {{ px: {_num(style['px'])}, weight: {style['weight']}, "
            f"tracking: {_num(style['tracking'])}, numeric: {str(style['numeric']).lower()}, "
            f"color: {_ts_string(style['color'])} }},"
        )
    lines.append("};")
    lines.append("")

    size_type = " | ".join(_ts_string(name) for name in SIZE_ORDER)
    lines.append(f"export type WidgetSizeKey = {size_type};")
    lines.append("")

    grid = theme["grid"]
    lines.append("export const ESTIMATED_HEIGHT: Readonly<Record<WidgetSizeKey, number>> = {")
    for key in SIZE_ORDER:
        lines.append(f"  {key}: {grid['estimatedHeight'][key]},")
    lines.append("};")
    lines.append("")

    lines.append("export interface SizeSpan {")
    lines.append("  readonly compact: number;")
    lines.append("  readonly regular: number;")
    lines.append("}")
    lines.append("")
    lines.append("export const SIZE_SPANS: Readonly<Record<WidgetSizeKey, SizeSpan>> = {")
    for key in SIZE_ORDER:
        compact, regular = grid["spanCompact"][key], grid["spanRegular"][key]
        lines.append(f"  {key}: {{ compact: {compact}, regular: {regular} }},")
    lines.append("};")
    lines.append("")

    columns_compact, columns_regular = grid["columns"]["compact"], grid["columns"]["regular"]
    gap_tiles, gap_broadsheet = grid["gap"]["tiles"], grid["gap"]["broadsheet"]
    lines.append("export const GRID = {")
    lines.append(f"  columns: {{ compact: {columns_compact}, regular: {columns_regular} }},")
    lines.append(f"  regularBreakpointPx: {grid['regularBreakpointPx']},")
    lines.append(f"  gap: {{ tiles: {gap_tiles}, broadsheet: {gap_broadsheet} }},")
    lines.append("} as const;")
    lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    out_dir = DEFAULT_OUT_DIR
    if args and args[0] == "--out":
        out_dir = Path(args[1])
    theme = load_theme()
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "tokens.css").write_text(render_css(theme), encoding="utf-8")
    (out_dir / "tokens.ts").write_text(render_ts(theme), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
