#!/usr/bin/env python3
"""Turn the three JSON catalogs into typed TypeScript the web app compiles against.

The iOS app gets the same three files (`metrics.json`, `widgets.json`, `presets.json`) copied
verbatim into its resource bundle and decodes them at runtime with hand-written `Codable`
structs (`ios/NBAStats/Core/Catalog.swift`). The web app instead gets them *embedded* as typed
TypeScript literals, for a reason specific to this design: five agents are building sixteen
widgets against a `Record<WidgetKind, WidgetView>` (`registry.ts`, emitted alongside this file),
and that guarantee — a widget kind missing its entry is a compile error, not a blank tile found
in week three — only exists if `WidgetKind` is a real TypeScript union the compiler checks
against, not a `string` read out of a JSON file fetched at runtime. Embedding the catalogs as
`as const` object literals gets that union, plus every other literal type (`MetricFormat`,
`ConfigFieldType`, …), for free from the same JSON that already is this project's single source
of truth — no second, hand-maintained set of TypeScript interfaces to let drift.

This generator never talks to the network and never re-derives a fact `contracts/*.json` already
states; it only re-shapes JSON into TypeScript syntax (which, for an object literal, JSON already
almost is) plus the union types TypeScript needs and JSON has no way to express.

Emits two files into ``web/src/generated/``:

* ``contracts.ts`` — the ``WidgetKind`` / ``MetricKey`` / ``MetricFormat`` / ``ConfigFieldType``
  unions, the three catalogs verbatim as frozen consts, and ``ERA_BOUNDARIES``.
* ``registry.ts`` — ``REGISTRY: Record<WidgetKind, RegistryEntry>``, one entry per widget kind
  with its ``sizes`` and ``defaultSize`` from the catalog and a ``component`` that is `null` until
  a widget directory exists on disk at ``web/src/widgets/<kind>/index.tsx``. This is deliberately
  read from the filesystem, not from ``web/src/widgets/PENDING.txt``: the two files are owned by
  different work packages that build in parallel, so the actual presence of a widget's own
  ``index.tsx`` is the one fact both a WP0 rerun (nothing built yet, every entry ``null``) and a
  later rerun after WP5 lands a widget (that one entry now a real import) can agree on without
  either package waiting on the other's commit.

Usage: ``python3 contracts/tools/gen_web_contracts.py`` writes both files into
``web/src/generated/``. ``--out DIR`` writes them into ``DIR`` instead, for
``scripts/check_contracts.py`` check (i) to diff a scratch copy against the committed one — see
``gen_web_tokens.py``'s module docstring for why a multi-file generator needs this instead of a
stdout-diff.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
CONTRACTS = ROOT / "contracts"
WIDGETS_DIR = ROOT / "web" / "src" / "widgets"
DEFAULT_OUT_DIR = ROOT / "web" / "src" / "generated"

BANNER = "// GENERATED by contracts/tools/gen_web_contracts.py — DO NOT EDIT."


def _load(name: str) -> dict[str, Any]:
    path = CONTRACTS / name
    if not path.is_file():
        print(f"{path}: does not exist", file=sys.stderr)
        raise SystemExit(1)
    return json.loads(path.read_text(encoding="utf-8"))


def _as_const_literal(document: Any, indent: int = 0) -> str:
    """JSON is already valid TypeScript object-literal syntax; the only thing it is missing is
    `as const` on the outermost value, so every string in it narrows to a literal type instead of
    widening to `string`. That one word is the entire reason `WidgetKind` below can be a real
    union instead of a `string` alias."""
    return json.dumps(document, indent=2)


def render_contracts(
    metrics: dict[str, Any], widgets: dict[str, Any], presets: dict[str, Any]
) -> str:
    widget_kinds = [w["kind"] for w in widgets["widgets"]]
    metric_keys = [m["key"] for m in metrics["metrics"]]
    metric_formats = [f["key"] for f in metrics["formats"]]
    config_field_types = list(widgets["configFieldTypes"])

    def union(values: list[str]) -> str:
        return " | ".join(json.dumps(v) for v in values)

    lines: list[str] = [BANNER, ""]
    lines.append(f"export type WidgetKind = {union(widget_kinds)};")
    lines.append(f"export const WIDGET_KINDS: readonly WidgetKind[] = {json.dumps(widget_kinds)};")
    lines.append("")
    lines.append(f"export type MetricKey = {union(metric_keys)};")
    lines.append("")
    lines.append(f"export type MetricFormat = {union(metric_formats)};")
    lines.append("")
    lines.append(f"export type ConfigFieldType = {union(config_field_types)};")
    lines.append("")
    lines.append(f"export const METRICS_DOCUMENT = {_as_const_literal(metrics)} as const;")
    lines.append("")
    lines.append(f"export const WIDGETS_DOCUMENT = {_as_const_literal(widgets)} as const;")
    lines.append("")
    lines.append(f"export const PRESETS_DOCUMENT = {_as_const_literal(presets)} as const;")
    lines.append("")
    lines.append("export interface EraBoundary {")
    lines.append("  readonly season: string;")
    lines.append("  readonly label: string;")
    lines.append("  readonly detail: string;")
    lines.append("}")
    lines.append("")
    lines.append(
        "/** `metrics.json#/eraBoundaries` — do not hand-write this table "
        "(WEB_DESIGN.md §0.1-F). */"
    )
    lines.append(
        "export const ERA_BOUNDARIES: readonly EraBoundary[] = METRICS_DOCUMENT.eraBoundaries;"
    )
    lines.append("")
    return "\n".join(lines)


def _widget_has_index_file(kind: str) -> bool:
    directory = WIDGETS_DIR / kind
    return (directory / "index.tsx").is_file() or (directory / "index.ts").is_file()


def render_registry(widgets: dict[str, Any]) -> str:
    imports: list[str] = []
    entries: list[str] = []
    for widget in widgets["widgets"]:
        kind = widget["kind"]
        sizes = json.dumps(widget["sizes"])
        default_size = json.dumps(widget["defaultSize"])
        if _widget_has_index_file(kind):
            local_name = "widget_" + kind
            imports.append(f'import {local_name} from "../widgets/{kind}/index";')
            # No `as WidgetComponent` here. A widget's default export already *is* a
            # `WidgetComponent` — that is the contract `REGISTRY`'s `Record<WidgetKind,
            # RegistryEntry>` annotation checks — so the assertion was redundant, and
            # `@typescript-eslint/no-unnecessary-type-assertion` (a type-aware rule, so it can
            # tell) raised one error per widget. That stayed invisible for as long as every
            # `component` was `null` and no cast was emitted at all; the first sync after the
            # sixteen widget directories landed turned `npm run lint` red with sixteen errors in
            # a generated file nobody is allowed to hand-edit. Worse, the assertion was actively
            # harmful: it would have *silenced* a genuine signature mismatch in a widget's
            # default export, which is exactly the compile error this registry exists to produce.
            component_expr = local_name
        else:
            component_expr = "null"
        entries.append(
            f"  {kind}: {{ component: {component_expr}, sizes: {sizes}, "
            f"defaultSize: {default_size} }},"
        )

    lines: list[str] = [
        BANNER,
        "//",
        "// A widget kind's `component` is `null` until `web/src/widgets/<kind>/index.tsx` exists",
        "// on disk (checked at generation time, not read from PENDING.txt — see the module",
        "// docstring in gen_web_contracts.py). Re-run `scripts/sync_contracts.sh` after adding a",
        "// widget directory to pick it up; nothing here needs to change by hand.",
        "",
        'import type { WidgetKind } from "./contracts";',
        'import type { WidgetSizeKey } from "./tokens";',
        *imports,
        "",
        "export interface WidgetViewProps {",
        "  readonly kind: WidgetKind;",
        "  readonly size: WidgetSizeKey;",
        "  readonly payload: unknown;",
        "}",
        "",
        "export type WidgetComponent = (props: WidgetViewProps) => JSX.Element | null;",
        "",
        "export interface RegistryEntry {",
        "  readonly component: WidgetComponent | null;",
        "  readonly sizes: readonly WidgetSizeKey[];",
        "  readonly defaultSize: WidgetSizeKey;",
        "}",
        "",
        "export const REGISTRY: Readonly<Record<WidgetKind, RegistryEntry>> = {",
        *entries,
        "};",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    out_dir = DEFAULT_OUT_DIR
    if args and args[0] == "--out":
        out_dir = Path(args[1])

    metrics = _load("metrics.json")
    widgets = _load("widgets.json")
    presets = _load("presets.json")

    out_dir.mkdir(parents=True, exist_ok=True)
    contracts_text = render_contracts(metrics, widgets, presets)
    (out_dir / "contracts.ts").write_text(contracts_text, encoding="utf-8")
    (out_dir / "registry.ts").write_text(render_registry(widgets), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
