"""Generate contracts/widgets.json - the shared widget catalog + config field schema."""
import json

def f(key, type_, label, **kw):
    d = {"key": key, "type": type_, "label": label, "required": kw.pop("required", False),
         "default": kw.pop("default", None)}
    d.update(kw)
    return d

SEASON     = f("season", "season", "Season", default="latest", required=True,
               help="A season string such as 2025-26, or 'latest' for the current season.")
SEASON_TYPE= f("seasonType", "enum", "Season Type", default="Regular Season", required=True,
               options=["Regular Season", "Playoffs", "Play In", "All Star", "Pre Season"])
PER_MODE   = f("perMode", "enum", "Per Mode", default="PerGame",
               options=["PerGame", "Totals", "Per36", "Per100"])

W = [
 {
  "kind": "stat_tile",
  "name": "Stat Tile",
  "summary": "One headline metric for a player or team, with optional supporting metrics and a sparkline.",
  "icon": "number.square",
  "sizes": ["small", "medium", "large"],
  "defaultSize": "small",
  "minRefreshSeconds": 300,
  "config": [
    f("subjectType", "enum", "Subject", default="player", required=True, options=["player", "team"]),
    f("subjectId", "subject", "Player or Team", required=True, dependsOn="subjectType"),
    f("metric", "metric", "Metric", default="ts_pct", required=True, metricScope="any"),
    f("secondaryMetrics", "metricList", "Supporting Metrics", default=["pts", "usg_pct"], maxItems=4),
    SEASON, SEASON_TYPE, PER_MODE,
    f("showSparkline", "bool", "Show Sparkline", default=True),
    f("sparklineWindow", "int", "Sparkline Games", default=15, min=5, max=82),
  ],
 },
 {
  "kind": "player_snapshot",
  "name": "Player Snapshot",
  "summary": "A player's full advanced slate for a season, with league percentile bars.",
  "icon": "person.crop.square",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 300,
  "config": [
    f("playerId", "player", "Player", required=True),
    SEASON, SEASON_TYPE,
    f("metrics", "metricList", "Metrics", required=True, metricScope="player",
      default=["ts_pct", "usg_pct", "ast_pct", "reb_pct", "off_rtg", "def_rtg", "net_rtg", "pie"], maxItems=12),
    f("showPercentiles", "bool", "Show League Percentiles", default=True),
  ],
 },
 {
  "kind": "leaderboard",
  "name": "Leaderboard",
  "summary": "Top players or teams ranked by any metric, with qualifier filters.",
  "icon": "list.number",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 600,
  "config": [
    f("subjectType", "enum", "Subject", default="player", required=True, options=["player", "team"]),
    f("metric", "metric", "Metric", default="pie", required=True, metricScope="any"),
    f("scope", "enum", "Scope", default="season", options=["season", "all_time"],
      help="'all_time' ranks the best single seasons in league history."),
    SEASON, SEASON_TYPE, PER_MODE,
    f("limit", "int", "Rows", default=10, min=3, max=50),
    f("minGames", "int", "Minimum Games", default=15, min=0, max=82),
    f("minMinutesPerGame", "double", "Minimum MPG", default=20.0, min=0.0, max=48.0),
    f("positions", "enumList", "Positions", default=[], options=["G", "F", "C"]),
    f("teamIds", "teamList", "Teams", default=[]),
    f("secondaryMetrics", "metricList", "Extra Columns", default=["pts", "min"], maxItems=3),
    f("ascending", "bool", "Reverse Order", default=False,
      help="Off means best-first using the metric's own direction."),
  ],
 },
 {
  "kind": "game_log",
  "name": "Game Log",
  "summary": "Recent games for a player, with configurable basic and advanced columns.",
  "icon": "tablecells",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 300,
  "config": [
    f("playerId", "player", "Player", required=True),
    SEASON, SEASON_TYPE,
    f("columns", "metricList", "Columns", required=True,
      default=["min", "pts", "reb", "ast", "ts_pct", "usg_pct", "plus_minus", "game_score"], maxItems=14),
    f("limit", "int", "Games", default=10, min=5, max=82),
    f("highlightSeasonBest", "bool", "Highlight Season Bests", default=True),
  ],
 },
 {
  "kind": "trend_chart",
  "name": "Trend",
  "summary": "A metric game by game, with a rolling average and an optional league baseline.",
  "icon": "chart.xyaxis.line",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 300,
  "config": [
    f("subjectType", "enum", "Subject", default="player", required=True, options=["player", "team"]),
    f("subjectIds", "subjectList", "Players or Teams", required=True, maxItems=4, dependsOn="subjectType"),
    f("metric", "metric", "Metric", default="ts_pct", required=True, metricScope="any"),
    SEASON, SEASON_TYPE,
    f("rollingWindow", "int", "Rolling Average Games", default=5, min=1, max=25),
    f("showLeagueAverage", "bool", "Show League Average", default=True),
    f("showRawPoints", "bool", "Show Individual Games", default=True),
  ],
 },
 {
  "kind": "four_factors",
  "name": "Four Factors",
  "summary": "Dean Oliver's four factors for a team, against the league average and the opponent.",
  "icon": "square.grid.2x2",
  "sizes": ["medium", "large"],
  "defaultSize": "medium",
  "minRefreshSeconds": 600,
  "config": [
    f("teamId", "team", "Team", required=True),
    SEASON, SEASON_TYPE,
    f("showOpponent", "bool", "Show Defensive Four Factors", default=True),
    f("comparison", "enum", "Compare Against", default="league", options=["league", "none"]),
  ],
 },
 {
  "kind": "shot_profile",
  "name": "Shot Profile",
  "summary": "Where the shots come from and how they fall, by court zone.",
  "icon": "scope",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 600,
  "availableFrom": "1996-97",
  "config": [
    f("subjectType", "enum", "Subject", default="player", required=True, options=["player", "team"]),
    f("subjectId", "subject", "Player or Team", required=True, dependsOn="subjectType"),
    SEASON, SEASON_TYPE,
    f("compareToLeague", "bool", "Compare to League", default=True),
  ],
 },
 {
  "kind": "comparison",
  "name": "Comparison",
  "summary": "Two to four players side by side on the metrics you choose, normalized to league percentiles.",
  "icon": "person.2",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 600,
  "config": [
    f("playerIds", "playerList", "Players", required=True, minItems=2, maxItems=4),
    f("metrics", "metricList", "Metrics", required=True, metricScope="player",
      default=["pts", "ts_pct", "usg_pct", "ast_pct", "reb_pct", "net_rtg"], maxItems=10),
    SEASON, SEASON_TYPE,
    f("normalization", "enum", "Scale", default="percentile", options=["percentile", "raw"]),
    f("style", "enum", "Style", default="bars", options=["bars", "radar", "table"]),
  ],
 },
 {
  "kind": "scoreboard",
  "name": "Scoreboard",
  "summary": "Every game on a slate with final scores and the best advanced line from each side.",
  "icon": "sportscourt",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 60,
  "config": [
    f("date", "date", "Date", default="latest", required=True,
      help="An ISO date, or 'latest' for the most recent completed slate."),
    f("showTopPerformers", "bool", "Show Top Performers", default=True),
    f("teamIds", "teamList", "Only These Teams", default=[]),
  ],
 },
 {
  "kind": "daily_movers",
  "name": "Daily Movers",
  "summary": "The biggest single-game performances from the last completed slate, versus each player's own season baseline.",
  "icon": "arrow.up.right",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 60,
  "config": [
    f("date", "date", "Date", default="latest", required=True),
    f("metric", "metric", "Metric", default="game_score", required=True, metricScope="player"),
    f("limit", "int", "Rows", default=8, min=3, max=25),
    f("minMinutes", "double", "Minimum Minutes", default=12.0, min=0.0, max=48.0),
    f("direction", "enum", "Direction", default="best", options=["best", "worst", "surprise"],
      help="'surprise' ranks by the largest gap against the player's own season average."),
  ],
 },
 {
  "kind": "team_efficiency",
  "name": "Team Efficiency",
  "summary": "League-wide offensive, defensive and net rating with pace.",
  "icon": "chart.bar.xaxis",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 600,
  "config": [
    SEASON, SEASON_TYPE,
    f("sortBy", "metric", "Sort By", default="net_rtg", metricScope="team"),
    f("conference", "enum", "Conference", default="all", options=["all", "East", "West"]),
    f("limit", "int", "Rows", default=30, min=5, max=30),
    f("style", "enum", "Style", default="table", options=["table", "scatter"]),
  ],
 },
 {
  "kind": "next_game_projection",
  "name": "Next Game",
  "summary": "A projected box score for a player's next game, with the interval and the factors behind it.",
  "icon": "function",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 600,
  "availableFrom": "1996-97",
  "config": [
    f("playerId", "player", "Player", required=True),
    f("stats", "metricList", "Project These", required=True, metricScope="player",
      default=["pts", "reb", "ast", "fg3m", "stl", "blk", "tov"], maxItems=8),
    f("opponentTeamId", "team", "Opponent Override", default=None,
      help="Leave empty to use the player's actual next scheduled opponent."),
    f("interval", "enum", "Interval", default="80", options=["80", "50", "none"],
      help="A projected mean without its interval is misleading; 80% is the paper's nominal level."),
    f("showCombo", "bool", "Show PTS+REB+AST", default=True,
      help="Uses the residual correlation, which widens the interval by about 13%."),
    f("showFactors", "bool", "Show Context Factors", default=True,
      help="Pace, opponent, venue and rest, each as a multiplier around 1.0."),
    SEASON, SEASON_TYPE,
  ],
 },
 {
  "kind": "projection_board",
  "name": "Tonight's Projections",
  "summary": "Tonight's projected lines for several players, each as a range with the season average marked.",
  "icon": "chart.dots.scatter",
  "sizes": ["large"],
  "defaultSize": "large",
  "minRefreshSeconds": 600,
  "availableFrom": "1996-97",
  "config": [
    f("date", "date", "Slate", default="latest", required=True),
    f("scope", "enum", "Players", default="favorites",
      options=["favorites", "league", "team"],
      help="'league' ranks by projected value across tonight's slate."),
    f("playerIds", "playerList", "Players", default=[], maxItems=12,
      help="Used when Players is set to a specific list; otherwise the scope decides."),
    f("teamId", "team", "Team", default=None),
    f("metrics", "metricList", "Lines", required=True, metricScope="player",
      default=["pts", "reb", "ast"], maxItems=6),
    f("limit", "int", "Rows", default=6, min=3, max=20),
    f("minMinutes", "double", "Minimum Projected Minutes", default=20.0, min=0.0, max=48.0),
    f("reference", "enum", "Reference Mark", default="season_average",
      options=["season_average", "career_average", "none"],
      help="The tick on the band. A projection is only meaningful against something."),
    SEASON_TYPE,
  ],
 },
 {
  "kind": "fantasy_draft_board",
  "name": "Draft Board",
  "summary": "Nine-category fantasy value for every player, ranked, with what each pick adds.",
  "icon": "checklist",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 600,
  # 3PM is the binding era boundary of a nine-category board: turnovers begin in 1977-78 and
  # steals and blocks in 1973-74, but a category league without threes is a different game.
  "availableFrom": "1979-80",
  "config": [
    f("season", "season", "Season", default="latest", required=True),
    f("scoring", "enum", "Scoring", default="categories", required=True,
      options=["categories", "espn_points", "yahoo_points"],
      help="Categories ranks on the nine z-scores; the other two use that site's default points."),
    f("puntCategories", "enumList", "Punt", default=[],
      options=["pts", "fg3m", "reb", "ast", "stl", "blk", "tov", "fg_pct", "ft_pct"],
      help="A punted category is weighted 0. The per-category numbers do not change, so a "
           "punt build and a balanced build stay comparable."),
    f("teams", "int", "Teams in League", default=12, min=2, max=30),
    f("rosterSpots", "int", "Roster Spots", default=13, min=1, max=25),
    f("poolSize", "int", "Players in the Pool", default=150, min=20, max=500,
      help="Who the z-scores are measured against. Teams x roster spots is the usual choice."),
    f("draftedPlayerIds", "playerList", "Already Drafted", default=[], maxItems=200),
    f("myPlayerIds", "playerList", "My Roster", default=[], maxItems=25,
      help="Sets the categories the board weighs your remaining need against."),
    f("limit", "int", "Rows", default=30, min=5, max=100),
    SEASON_TYPE,
  ],
 },
 {
  "kind": "fantasy_trade",
  "name": "Trade Analyzer",
  "summary": "What a trade gains and costs, category by category, with the roster spots it moves.",
  "icon": "arrow.left.arrow.right",
  "sizes": ["large"],
  "defaultSize": "large",
  "minRefreshSeconds": 600,
  "availableFrom": "1979-80",
  "config": [
    f("season", "season", "Season", default="latest", required=True),
    # No minItems: the widget ships empty and the reader fills both sides in. The resolver
    # says "add at least one player to each side" rather than the catalog rejecting the
    # preset that introduces it.
    f("givePlayerIds", "playerList", "You Give", default=[], maxItems=4),
    f("getPlayerIds", "playerList", "You Get", default=[], maxItems=4),
    f("puntCategories", "enumList", "Punt", default=[],
      options=["pts", "fg3m", "reb", "ast", "stl", "blk", "tov", "fg_pct", "ft_pct"]),
    f("poolSize", "int", "Players in the Pool", default=150, min=20, max=500),
    f("fairBand", "double", "Fair Within", default=0.75, min=0.0, max=10.0,
      help="Net z-sum per game inside this band reads as fair. Set it against your league's "
           "own spread, which the widget reports."),
    f("clearBand", "double", "Clear Win Beyond", default=2.0, min=0.0, max=20.0),
    f("showSensitivity", "bool", "Show Scenario Range", default=True,
      help="Recomputes the trade under four named what-ifs. A range, never a probability."),
    SEASON_TYPE,
  ],
 },
 {
  "kind": "career_arc",
  "name": "Career Arc",
  "summary": "A metric season by season across a whole career, with era availability marked.",
  "icon": "waveform.path.ecg",
  "sizes": ["medium", "large"],
  "defaultSize": "large",
  "minRefreshSeconds": 3600,
  "config": [
    f("playerId", "player", "Player", required=True),
    f("metric", "metric", "Metric", default="per", required=True, metricScope="player"),
    f("seasonType", "enum", "Season Type", default="Regular Season",
      options=["Regular Season", "Playoffs"]),
    f("includePlayoffs", "bool", "Overlay Playoffs", default=True),
    f("xAxis", "enum", "X Axis", default="season", options=["season", "age"]),
  ],
 },
]

for w in W:
    w.setdefault("availableFrom", None)
    assert w["defaultSize"] in w["sizes"], w["kind"]
    keys = [c["key"] for c in w["config"]]
    assert len(keys) == len(set(keys)), w["kind"]

doc = {
    "schemaVersion": 1,
    "sizes": [
        {"key": "small",  "columnsCompact": 1, "columnsRegular": 1, "height": 148,
         "name": "Small",  "summary": "One column, headline value only."},
        {"key": "medium", "columnsCompact": 2, "columnsRegular": 2, "height": 232,
         "name": "Medium", "summary": "Full width on iPhone, half width on iPad."},
        {"key": "large",  "columnsCompact": 2, "columnsRegular": 4, "height": 360,
         "name": "Large",  "summary": "Full width, tall enough for tables and charts."},
    ],
    "gridColumns": {"compact": 2, "regular": 4},
    "configFieldTypes": [
        "season", "enum", "enumList", "metric", "metricList", "player", "playerList",
        "team", "teamList", "subject", "subjectList", "int", "double", "bool", "date",
    ],
    "widgets": W,
}
print(json.dumps(doc, indent=2))
