import Foundation
import XCTest
@testable import Hardwood

/// The recorded league bodies in `contracts/fixtures/leagues/{nba,el}/` and the four tile
/// fixtures are generated by the backend from the same code that serves the routes, so decoding
/// them is the test that the Swift types and the server agree. `scripts/sync_contracts.sh` copies
/// them into the bundles as `league_<nba|el>_<name>.json`.
///
/// Decoding without a throw is the weakest claim: every property is Optional, so a struct that
/// had lost all its keys would still decode. The tests after the table therefore also check values
/// that only arrive when the keys are right, and `scripts/check_swift_portability.py` rule P14
/// compares every key of every fixture with the struct's properties.
final class LeaguePayloadDecodingTests: XCTestCase {

    private let decoder = APIClient.makeDecoder()

    // MARK: - The table

    /// One recorded body and the type that must hold it.
    private struct FixtureCase {
        let name: String
        let decode: (Data, JSONDecoder) throws -> Void
    }

    private func fixtureCase<T: Decodable>(_ name: String, _ type: T.Type) -> FixtureCase {
        FixtureCase(name: name) { data, decoder in
            _ = try decoder.decode(type, from: data)
        }
    }

    private var allCases: [FixtureCase] {
        var cases: [FixtureCase] = []
        cases += nbaCases
        cases += euroLeagueCases
        cases += widgetCases
        return cases
    }

    private var nbaCases: [FixtureCase] {
        [
            fixtureCase("league_nba_leagues", [LeagueInfo].self),
            fixtureCase("league_nba_team_matchup", LeagueMatchup.self),
            fixtureCase("league_nba_game_matchup", LeagueMatchup.self),
            fixtureCase("league_nba_defense_by_position", LeagueDefenseDocument.self),
            fixtureCase("league_nba_defense_by_position_table", LeagueDefenseDocument.self),
            fixtureCase("league_nba_slate_projections", LeagueSlateProjections.self),
            fixtureCase("league_nba_game_projection_detail", LeagueGameProjectionDetail.self),
            fixtureCase("league_nba_projection_review", LeagueProjectionReview.self),
            fixtureCase("league_nba_availability_report", LeagueAvailabilityReport.self),
            fixtureCase("league_nba_availability_report_demo", LeagueAvailabilityReport.self),
            fixtureCase("league_nba_availability_review_queue", LeagueReviewQueue.self),
            fixtureCase("league_nba_news", LeagueNewsList.self),
            fixtureCase("league_nba_sources", LeagueSourceList.self),
            fixtureCase("league_nba_model_settings", LeagueModelSettings.self)
        ]
    }

    private var euroLeagueCases: [FixtureCase] {
        var cases: [FixtureCase] = euroLeagueSharedCases
        cases += euroLeagueOnlyCases
        return cases
    }

    private var euroLeagueSharedCases: [FixtureCase] {
        [
            fixtureCase("league_el_team_matchup", LeagueMatchup.self),
            fixtureCase("league_el_game_matchup", LeagueMatchup.self),
            fixtureCase("league_el_defense_by_position", LeagueDefenseDocument.self),
            fixtureCase("league_el_defense_by_position_table", LeagueDefenseDocument.self),
            fixtureCase("league_el_slate_projections", LeagueSlateProjections.self),
            fixtureCase("league_el_game_projection_detail", LeagueGameProjectionDetail.self),
            fixtureCase("league_el_projection_review", LeagueProjectionReview.self),
            fixtureCase("league_el_availability_report", LeagueAvailabilityReport.self),
            fixtureCase("league_el_review_queue", LeagueReviewQueue.self),
            fixtureCase("league_el_news", LeagueNewsList.self),
            fixtureCase("league_el_sources", LeagueSourceList.self),
            fixtureCase("league_el_model_settings", LeagueModelSettings.self)
        ]
    }

    private var euroLeagueOnlyCases: [FixtureCase] {
        [
            fixtureCase("league_el_meta", ElMeta.self),
            fixtureCase("league_el_teams", ElTeamsTable.self),
            fixtureCase("league_el_club_view", ElClubView.self),
            fixtureCase("league_el_round_view", ElRoundView.self),
            fixtureCase("league_el_round_view_complete", ElRoundView.self),
            fixtureCase("league_el_round_scorers", ElRoundScorers.self),
            fixtureCase("league_el_ratings", ElRatingsTable.self),
            fixtureCase("league_el_games", ElGamesList.self),
            fixtureCase("league_el_box_score", ElBoxScore.self),
            fixtureCase("league_el_player_stats", ElPlayerStatsTable.self),
            fixtureCase("league_el_player_detail", ElPlayerDetail.self),
            fixtureCase("league_el_player_gamelog", ElPlayerGameLog.self),
            fixtureCase("league_el_method", ElMethod.self)
        ]
    }

    /// The four tile payloads: the NBA's are the flat `widget_<kind>` fixtures, the EuroLeague's
    /// are the `league_el_widget_<kind>` copies.
    private var widgetCases: [FixtureCase] {
        [
            fixtureCase("widget_team_matchup", LeagueMatchup.self),
            fixtureCase("widget_defense_by_position", LeagueDefenseDocument.self),
            fixtureCase("widget_availability_report", LeagueAvailabilityReport.self),
            fixtureCase("widget_slate_projections", LeagueSlateProjections.self),
            fixtureCase("league_el_widget_team_matchup", LeagueMatchup.self),
            fixtureCase("league_el_widget_defense_by_position", LeagueDefenseDocument.self),
            fixtureCase("league_el_widget_availability_report", LeagueAvailabilityReport.self),
            fixtureCase("league_el_widget_slate_projections", LeagueSlateProjections.self)
        ]
    }

    /// Reads one fixture and decodes it as `T`. A fixture that is not bundled skips the test (it
    /// names the file); one that is bundled and does not decode fails it, with the key path.
    private func loadOrSkip<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        guard let data = TestBundles.fixtureData(named: name) else {
            throw XCTSkip("\(name).json is not bundled; run scripts/sync_contracts.sh.")
        }
        return try decoder.decode(type, from: data)
    }

    // MARK: - Every recorded body decodes

    func testEveryLeagueFixtureDecodes() throws {
        var missing: [String] = []
        var failures: [String] = []
        for entry in allCases {
            guard let data = TestBundles.fixtureData(named: entry.name) else {
                missing.append(entry.name)
                continue
            }
            do {
                try entry.decode(data, decoder)
            } catch let error as DecodingError {
                failures.append("\(entry.name): \(APIError.describe(error))")
            } catch {
                failures.append("\(entry.name): \(error.localizedDescription)")
            }
        }
        XCTAssertTrue(failures.isEmpty, "Fixtures that do not decode:\n" + failures.joined(separator: "\n"))
        try XCTSkipUnless(missing.isEmpty, """
            Not in a test-visible bundle yet: \(missing.joined(separator: ", ")). Generate them with \
            `python3 -m nbastats.nba_matchup.fixtures_export --write` and \
            `python3 -m nbastats.euroleague.fixtures_export --write` from backend/, then copy them in \
            with scripts/sync_contracts.sh.
            """)
    }

    /// An empty object decodes into every payload type: one missing key must never cost a screen.
    func testAnEmptyObjectDecodesIntoEveryPayloadType() throws {
        let data = Data("{}".utf8)
        XCTAssertNoThrow(try decoder.decode(LeagueMatchup.self, from: data))
        XCTAssertNoThrow(try decoder.decode(LeagueDefenseDocument.self, from: data))
        XCTAssertNoThrow(try decoder.decode(LeagueSlateProjections.self, from: data))
        XCTAssertNoThrow(try decoder.decode(LeagueGameProjectionDetail.self, from: data))
        XCTAssertNoThrow(try decoder.decode(LeagueProjectionReview.self, from: data))
        XCTAssertNoThrow(try decoder.decode(LeagueAvailabilityReport.self, from: data))
        XCTAssertNoThrow(try decoder.decode(LeagueNewsList.self, from: data))
        XCTAssertNoThrow(try decoder.decode(LeagueSourceList.self, from: data))
        XCTAssertNoThrow(try decoder.decode(ElMeta.self, from: data))
        XCTAssertNoThrow(try decoder.decode(ElClubView.self, from: data))
        XCTAssertNoThrow(try decoder.decode(ElRoundView.self, from: data))
        XCTAssertNoThrow(try decoder.decode(ElBoxScore.self, from: data))
        XCTAssertNoThrow(try decoder.decode(ElPlayerDetail.self, from: data))
        let empty = try decoder.decode(LeagueMatchup.self, from: data)
        XCTAssertNil(empty.teams)
        XCTAssertEqual(empty, LeagueMatchup())
    }

    /// A key a future server adds is ignored, not an error.
    func testUnknownKeysAreIgnored() throws {
        let json = #"{"league": "nba", "someFutureKey": {"nested": [1, 2, 3]}, "notes": ["kept"]}"#
        let value = try decoder.decode(LeagueMatchup.self, from: Data(json.utf8))
        XCTAssertEqual(value.league, "nba")
        XCTAssertEqual(value.notes, ["kept"])
    }

    // MARK: - The values the screens depend on arrive

    /// The user's own question: each team's latest score, points per game, points allowed per
    /// game, and the same over a recent window.
    func testMatchupCarriesLatestScoreAveragesAndPointsAllowed() throws {
        let matchup = try loadOrSkip(LeagueMatchup.self, "league_nba_team_matchup")
        let teams = try XCTUnwrap(matchup.teams)
        XCTAssertEqual(teams.count, 2)
        XCTAssertEqual(teams.map { $0.side }, ["home", "away"])
        for team in teams {
            XCTAssertNotNil(team.pointsPerGame)
            XCTAssertNotNil(team.pointsAllowedPerGame)
            XCTAssertNotNil(team.latestGame?.teamScore)
            XCTAssertNotNil(team.latestGame?.opponentScore)
            XCTAssertNotNil(team.latestGame?.result)
            XCTAssertNotNil(team.lastN?.pointsAllowedPerGame)
            XCTAssertNotNil(team.record?.wins)
        }
        XCTAssertEqual(matchup.projection?.model?.computedAfterTipoff, false)
    }

    /// Points allowed by opponent position: a team's buckets, and the all-teams table.
    func testDefenseDocumentDecodesAsTeamAndAsTable() throws {
        let team = try loadOrSkip(LeagueDefenseDocument.self, "league_nba_defense_by_position")
        let table = try loadOrSkip(LeagueDefenseDocument.self, "league_nba_defense_by_position_table")
        XCTAssertFalse(team.isLeagueTable)
        XCTAssertEqual(team.buckets?.compactMap { $0.position }, ["G", "F", "C", "unknown"])
        XCTAssertNotNil(team.pointsAllowedPerGame)
        XCTAssertNotNil(team.reconciliation?.sumOfBuckets)
        XCTAssertTrue(table.isLeagueTable)
        XCTAssertFalse(table.teams?.isEmpty ?? true)
        XCTAssertNotNil(table.teams?.first?.buckets)
    }

    /// A band the server did not send stays nil: it must render as an em dash, never "typical".
    func testBandsThatAreNotSentStayNil() throws {
        let table = try loadOrSkip(LeagueDefenseDocument.self, "league_el_defense_by_position_table")
        let buckets = (table.teams ?? []).flatMap { $0.buckets ?? [] }
        XCTAssertFalse(buckets.isEmpty)
        XCTAssertTrue(buckets.allSatisfy { $0.band == nil })
        XCTAssertEqual(LeagueFormatting.bandWord(buckets.first?.band), Formatting.emDash)
        XCTAssertEqual(table.teams?.first?.withheld?.reason, "minimumGames")
    }

    /// `computedAfterTipoff` is tri-state: absent on the slate-level block, a Bool per game.
    func testSlateModelBlockHasNoTipoffFlagButEveryGameHasOne() throws {
        let slate = try loadOrSkip(LeagueSlateProjections.self, "league_el_slate_projections")
        XCTAssertNil(slate.model?.computedAfterTipoff)
        let games = try XCTUnwrap(slate.games)
        XCTAssertFalse(games.isEmpty)
        XCTAssertTrue(games.allSatisfy { $0.model?.computedAfterTipoff != nil })
        XCTAssertNotNil(slate.round)
    }

    /// Every availability entry names its source, which is how the screen can show one.
    func testAvailabilityEntriesCarryTheirSource() throws {
        let report = try loadOrSkip(LeagueAvailabilityReport.self, "league_el_availability_report")
        let entries = (report.teams ?? []).flatMap { $0.entries ?? [] }
        XCTAssertFalse(entries.isEmpty)
        XCTAssertTrue(entries.allSatisfy { $0.source?.kind != nil && $0.source?.label != nil })
        XCTAssertTrue(entries.allSatisfy { $0.source?.publishedAt != nil })
        XCTAssertEqual(report.state, "fresh")
    }

    /// The team summary's counts are whole numbers (the design allowed a list; the server sends Int).
    func testAvailabilitySummaryCountsAreIntegers() throws {
        let matchup = try loadOrSkip(LeagueMatchup.self, "league_nba_team_matchup")
        let summary = try XCTUnwrap(matchup.teams?.first?.availability)
        XCTAssertNotNil(summary.out)
        XCTAssertEqual(LeagueAvailabilitySummary.count(summary.out), summary.out)
        XCTAssertNil(LeagueAvailabilitySummary.count(nil))
    }

    func testNewsListReadsItemsAndIsEmptyWhenThereAreNone() throws {
        let nba = try loadOrSkip(LeagueNewsList.self, "league_nba_news")
        let euroLeague = try loadOrSkip(LeagueNewsList.self, "league_el_news")
        XCTAssertFalse(nba.allItems.isEmpty)
        XCTAssertNotNil(nba.allItems.first?.title)
        XCTAssertNotNil(nba.allItems.first?.link)
        XCTAssertNotNil(nba.allItems.first?.sourceName)
        XCTAssertTrue(euroLeague.allItems.isEmpty)
    }

    /// The box score's per-player key is `stats`, never `line` (the backend refuses that word).
    func testBoxScorePlayersUseTheStatsKey() throws {
        let box = try loadOrSkip(ElBoxScore.self, "league_el_box_score")
        let players = (box.teams ?? []).flatMap { $0.players ?? [] }
        let played = players.filter { $0.participation == "played" }
        XCTAssertFalse(played.isEmpty)
        XCTAssertTrue(played.allSatisfy { $0.stats?.pts != nil })
        XCTAssertEqual(played.first?.resolvedLine, played.first?.stats)
        XCTAssertNotNil(box.partials?.home)
        XCTAssertEqual(box.game?.status, "final")
        XCTAssertNotNil(box.teams?.first?.totals?.pts)
    }

    /// The projected PIR is always nil (the workbook's rates cannot produce one); the rest of the
    /// per-game line is there.
    func testSquadPerGameProjectionHasNoPir() throws {
        let club = try loadOrSkip(ElClubView.self, "league_el_club_view")
        let squad = try XCTUnwrap(club.squad)
        XCTAssertFalse(squad.isEmpty)
        XCTAssertNotNil(squad.first?.perGame?.pts)
        XCTAssertTrue(squad.allSatisfy { $0.perGame?.pir == nil })
        XCTAssertNotNil(club.scoring?.pointsAllowedPerGame)
        XCTAssertNotNil(club.nextGame?.tipoffUtc)
    }

    /// A game-log row names the player's own `club` and carries a W or L result and the scores.
    func testGameLogRowsCarryClubResultAndScores() throws {
        let log = try loadOrSkip(ElPlayerGameLog.self, "league_el_player_gamelog")
        let rows = try XCTUnwrap(log.games)
        XCTAssertFalse(rows.isEmpty)
        for row in rows {
            XCTAssertNotNil(row.club?.clubCode)
            XCTAssertTrue(["W", "L"].contains(row.result ?? ""))
            XCTAssertNotNil(row.teamScore)
            XCTAssertNotNil(row.opponentScore)
        }
    }

    func testMetaListsRoundsSeasonsAndClubs() throws {
        let meta = try loadOrSkip(ElMeta.self, "league_el_meta")
        XCTAssertFalse(meta.rounds?.isEmpty ?? true)
        XCTAssertEqual(meta.seasons?.first?.code, "E2026")
        XCTAssertEqual(meta.currentSeasonCode, "E2026")
        XCTAssertEqual(meta.regulationMinutes, 40)
        XCTAssertFalse(meta.clubs?.isEmpty ?? true)
        XCTAssertNotNil(meta.dayOneNotice)
        XCTAssertEqual(meta.freshness?.isDemo, true)
    }

    /// `/v1/leagues` is a bare array, and the EuroLeague's prefix is read from it.
    func testLeaguesIsABareArrayWithPrefixes() throws {
        let leagues = try loadOrSkip([LeagueInfo].self, "league_nba_leagues")
        XCTAssertEqual(leagues.compactMap { $0.key }, ["nba", "euroleague"])
        XCTAssertEqual(leagues.compactMap { $0.apiPrefix }, ["/v1", "/v1/el"])
        XCTAssertEqual(leagues.first?.regulationMinutes, 48)
    }

    // MARK: - The invented previews

    func testEveryPreviewLiteralDecodesToSomethingNonEmpty() {
        XCTAssertNotNil(LeaguePreviewData.decode(LeagueMatchup.self, json: LeaguePreviewData.matchupJSON))
        XCTAssertNotNil(LeaguePreviewData.decode(LeagueDefenseDocument.self, json: LeaguePreviewData.defenseJSON))
        XCTAssertNotNil(LeaguePreviewData.decode(LeagueAvailabilityReport.self, json: LeaguePreviewData.availabilityJSON))
        XCTAssertNotNil(LeaguePreviewData.decode(LeagueSlateProjections.self, json: LeaguePreviewData.slateJSON))
        XCTAssertNotNil(LeaguePreviewData.decode(ElRoundView.self, json: LeaguePreviewData.roundJSON))
        XCTAssertNotNil(LeaguePreviewData.decode(ElClubView.self, json: LeaguePreviewData.clubJSON))
        XCTAssertNil(LeaguePreviewData.decode(LeagueMatchup.self, json: "not json"))
    }

    /// Values that only survive when the preview's keys match the struct, and that every preview
    /// is plainly an invented league.
    func testPreviewsCarryValuesAndSayTheyAreInvented() {
        XCTAssertEqual(LeagueMatchup.preview.teams?.count, 2)
        XCTAssertNotNil(LeagueMatchup.preview.teams?.first?.latestGame?.teamScore)
        XCTAssertNotNil(LeagueMatchup.preview.teams?.first?.pointsAllowedPerGame)
        XCTAssertEqual(LeagueMatchup.preview.projection?.summary, "ZZB by 2.5")
        XCTAssertEqual(LeagueDefenseDocument.preview.buckets?.count, 3)
        XCTAssertEqual(LeagueDefenseDocument.preview.withheld?.reason, "minimumGames")
        XCTAssertEqual(LeagueAvailabilityReport.preview.teams?.count, 2)
        XCTAssertNotNil(LeagueAvailabilityReport.preview.teams?.first?.entries?.first?.source?.label)
        XCTAssertEqual(LeagueSlateProjections.preview.games?.count, 2)
        XCTAssertEqual(ElRoundView.preview.round, 3)
        XCTAssertEqual(ElClubView.preview.squad?.count, 2)
        XCTAssertNil(ElClubView.preview.squad?.first?.perGame?.pir)

        XCTAssertEqual(LeagueMatchup.preview.freshness?.isDemo, true)
        XCTAssertEqual(LeagueDefenseDocument.preview.freshness?.isDemo, true)
        XCTAssertEqual(LeagueAvailabilityReport.preview.freshness?.isDemo, true)
        XCTAssertEqual(LeagueSlateProjections.preview.freshness?.isDemo, true)
        XCTAssertEqual(ElRoundView.preview.freshness?.isDemo, true)
        XCTAssertEqual(ElClubView.preview.freshness?.isDemo, true)
    }

    // MARK: - Encoding

    /// A payload re-encodes and decodes to an equal value (the disk cache stores the encoded form).
    func testPayloadsSurviveAnEncodeDecodeRoundTrip() throws {
        let original = LeagueMatchup.preview
        let data = try APIClient.makeEncoder().encode(original)
        let again = try decoder.decode(LeagueMatchup.self, from: data)
        XCTAssertEqual(again, original)
    }

    /// A nil property is left out of a write body, and the NBA body has no club or label fields
    /// (the server refuses an unknown field with a 400).
    func testWriteBodiesOmitNilKeysAndTheLeaguesHaveTheirOwn() throws {
        let euroLeague = ElStatusWrite(clubCode: "ZZA",
                                       status: "out",
                                       sourceLabel: "Club statement",
                                       sourcePublishedAt: "2026-10-02T12:00:00Z",
                                       playerName: "Tobin Marlowe")
        let euroLeagueKeys = try keys(of: euroLeague)
        XCTAssertEqual(euroLeagueKeys, ["clubCode", "playerName", "sourceLabel", "sourcePublishedAt", "status"])

        let nba = NbaStatusWrite(playerId: 2544, status: "questionable", note: "Ankle")
        let nbaKeys = try keys(of: nba)
        XCTAssertEqual(nbaKeys, ["note", "playerId", "status"])
        XCTAssertFalse(nbaKeys.contains("sourceLabel"))
        XCTAssertFalse(nbaKeys.contains("clubCode"))

        let link = LeagueLinkWrite(title: "A headline", link: "https://news.example.org/a", sourceName: "Demo Daily")
        XCTAssertEqual(try keys(of: link), ["link", "sourceName", "title"])
    }

    private func keys<T: Encodable>(of value: T) throws -> [String] {
        let data = try APIClient.makeEncoder().encode(value)
        let object = try JSONSerialization.jsonObject(with: data)
        let dictionary = try XCTUnwrap(object as? [String: Any])
        return dictionary.keys.sorted()
    }
}
