import Foundation
import XCTest
@testable import Hardwood

/// The golden fixtures in `ios/NBAStatsTests/Fixtures/` are generated by the backend from the
/// same contract the Swift types are written against, so decoding them is the one test that
/// actually proves the two sides agree.
///
/// Every test here also asserts against the payload type's own `preview` value, so a missing
/// fixture directory turns the suite into a skip plus a set of still-meaningful assertions rather
/// than a green run that proved nothing.
final class PayloadDecodingTests: XCTestCase {

    private let decoder = APIClient.makeDecoder()

    private func requireFixtures() throws {
        try XCTSkipUnless(TestBundles.hasWidgetFixtures, """
            No golden fixtures are in a test-visible bundle. They are generated by the backend \
            into contracts/fixtures/ and copied to ios/NBAStatsTests/Fixtures/ by \
            scripts/sync_contracts.sh; run that and add the folder to the HardwoodTests target.
            """)
    }

    private func fixture(_ name: String) throws -> Data {
        try XCTUnwrap(TestBundles.fixtureData(named: name), "\(name).json is not in any test bundle")
    }

    // MARK: - Every widget fixture decodes into its payload type

    func testEveryWidgetKindHasAFixtureThatDecodes() throws {
        try requireFixtures()
        var decoded: [WidgetKind: WidgetPayload] = [:]
        for kind in WidgetKind.allCases {
            let data = try fixture("widget_\(kind.rawValue)")
            let payload = try WidgetPayload.decode(kind: kind, from: data, using: decoder)
            XCTAssertEqual(payload.kind, kind, "widget_\(kind.rawValue).json decoded into the wrong case")
            decoded[kind] = payload
        }
        XCTAssertEqual(decoded.count, WidgetKind.allCases.count)
        XCTAssertEqual(decoded.count, 12)
    }

    /// A payload that decodes has to survive being written to the disk cache and read back, which
    /// is exactly an encode/decode round trip through the same coders the app uses.
    func testEveryWidgetFixtureSurvivesARoundTrip() throws {
        try requireFixtures()
        let encoder = APIClient.makeEncoder()
        for kind in WidgetKind.allCases {
            let data = try fixture("widget_\(kind.rawValue)")
            let payload = try WidgetPayload.decode(kind: kind, from: data, using: decoder)
            let reEncoded = try encoder.encode(payload)
            let again = try WidgetPayload.decode(kind: kind, from: reEncoded, using: decoder)
            XCTAssertEqual(again, payload, "\(kind.rawValue) changed on the way through the cache")
        }
    }

    // MARK: - Per-kind content

    func testStatTileFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(StatTilePayload.self, from: try fixture("widget_stat_tile"))
        XCTAssertFalse(payload.subject.displayName.isEmpty)
        XCTAssertFalse(payload.primary.metric.isEmpty)
        XCTAssertFalse(payload.primary.displayValue.isEmpty)
        XCTAssertFalse(payload.sparkline.isEmpty)
        // And the preview agrees on the shape, so this test says something even with no fixture.
        XCTAssertEqual(StatTilePayload.preview.primary.metric, "ts_pct")
        XCTAssertFormatted(StatTilePayload.preview.primary.displayValue, "61.5%")
    }

    func testPlayerSnapshotFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(PlayerSnapshotPayload.self, from: try fixture("widget_player_snapshot"))
        XCTAssertGreaterThan(payload.player.playerId, 0)
        XCTAssertFalse(payload.metrics.isEmpty)
        XCTAssertFalse(PlayerSnapshotPayload.preview.metrics.isEmpty)
    }

    func testLeaderboardFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(LeaderboardPayload.self, from: try fixture("widget_leaderboard"))
        XCTAssertFalse(payload.rows.isEmpty)
        XCTAssertFalse(payload.metric.key.isEmpty)
        XCTAssertEqual(payload.rows.first?.rank, 1, "The leaderboard does not start at rank 1")
        // Ranks ascend, and every row names a subject.
        XCTAssertEqual(payload.rows.map { $0.rank }, payload.rows.map { $0.rank }.sorted())
        for row in payload.rows {
            XCTAssertFalse(row.subjectName.isEmpty)
            XCTAssertFalse(row.id.isEmpty)
        }
        XCTAssertEqual(LeaderboardPayload.preview.metric.key, "ts_pct")
        XCTAssertFalse(LeaderboardPayload.preview.rows.isEmpty)
    }

    func testGameLogFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(GameLogPayload.self, from: try fixture("widget_game_log"))
        XCTAssertFalse(payload.columns.isEmpty)
        XCTAssertFalse(payload.rows.isEmpty)
        for row in payload.rows {
            XCTAssertFalse(row.gameId.isEmpty)
            XCTAssertFalse(row.date.isEmpty)
            XCTAssertFalse(row.matchupText.isEmpty)
        }
        XCTAssertFalse(GameLogPayload.preview.rows.isEmpty)
    }

    func testTrendChartFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(TrendChartPayload.self, from: try fixture("widget_trend_chart"))
        XCTAssertFalse(payload.series.isEmpty)
        let points = payload.series.flatMap { $0.points }
        XCTAssertFalse(points.isEmpty)
        // A point with no value is a real case: it must survive as nil, not become zero.
        for point in points {
            XCTAssertFalse(point.x.isEmpty)
            if let y = point.y { XCTAssertTrue(y.isFinite) }
        }
        XCTAssertFalse(TrendChartPayload.preview.series.isEmpty)
    }

    func testFourFactorsFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(FourFactorsPayload.self, from: try fixture("widget_four_factors"))
        XCTAssertFalse(payload.team.abbr.isEmpty)
        XCTAssertEqual(payload.offense.count, 4, "The four factors are four")
        for entry in payload.offense {
            XCTAssertFalse(entry.key.isEmpty)
            XCTAssertFalse(entry.label.isEmpty)
            XCTAssertFalse(entry.displayValue.isEmpty)
        }
        // The contract fixes the order and the weights.
        XCTAssertEqual(payload.offense.map { $0.weight }, [0.40, 0.25, 0.20, 0.15])
        XCTAssertEqual(FourFactorsPayload.preview.offense.count, 4)
    }

    func testShotProfileFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(ShotProfilePayload.self, from: try fixture("widget_shot_profile"))
        XCTAssertFalse(payload.zones.isEmpty)
        XCTAssertEqual(payload.zones.map { $0.zone },
                       ["rim", "paint_non_rim", "mid_range", "corner_three", "above_break_three"],
                       "The contract fixes the zone order")
        XCTAssertFalse(ShotProfilePayload.preview.zones.isEmpty)
    }

    func testComparisonFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(ComparisonPayload.self, from: try fixture("widget_comparison"))
        XCTAssertGreaterThanOrEqual(payload.subjects.count, 2, "A comparison needs at least two subjects")
        XCTAssertFalse(payload.metrics.isEmpty)
        for subject in payload.subjects {
            XCTAssertFalse(subject.displayName.isEmpty)
            XCTAssertFalse(subject.id.isEmpty)
        }
        XCTAssertGreaterThanOrEqual(ComparisonPayload.preview.subjects.count, 2)
    }

    func testScoreboardFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(ScoreboardPayload.self, from: try fixture("widget_scoreboard"))
        XCTAssertFalse(payload.date.isEmpty)
        XCTAssertFalse(payload.games.isEmpty)
        for entry in payload.games {
            // The `GameRef` is flattened into the game object; decoding it is the point.
            XCTAssertFalse(entry.game.gameId.isEmpty)
            XCTAssertFalse(entry.game.home.abbr.isEmpty)
            XCTAssertFalse(entry.game.away.abbr.isEmpty)
            if entry.game.status == .final {
                XCTAssertNotNil(entry.game.homePts)
                XCTAssertNotNil(entry.game.awayPts)
            }
        }
        XCTAssertFalse(ScoreboardPayload.preview.games.isEmpty)
    }

    func testDailyMoversFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(DailyMoversPayload.self, from: try fixture("widget_daily_movers"))
        XCTAssertFalse(payload.date.isEmpty)
        XCTAssertFalse(payload.rows.isEmpty)
        XCTAssertFalse(payload.metric.key.isEmpty)
        for row in payload.rows {
            XCTAssertGreaterThan(row.player.playerId, 0)
            XCTAssertFalse(row.matchupText.isEmpty)
        }
        XCTAssertFalse(DailyMoversPayload.preview.rows.isEmpty)
    }

    func testTeamEfficiencyFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(TeamEfficiencyPayload.self, from: try fixture("widget_team_efficiency"))
        XCTAssertFalse(payload.rows.isEmpty)
        XCTAssertNotNil(payload.leagueAverageValue("off_rtg"))
        for row in payload.rows {
            XCTAssertGreaterThan(row.team.teamId, 0)
            XCTAssertFalse(row.recordText.isEmpty)
        }
        XCTAssertFalse(TeamEfficiencyPayload.preview.rows.isEmpty)
    }

    func testCareerArcFixture() throws {
        try requireFixtures()
        let payload = try decoder.decode(CareerArcPayload.self, from: try fixture("widget_career_arc"))
        XCTAssertFalse(payload.seasons.isEmpty)
        XCTAssertFalse(payload.metric.key.isEmpty)
        for season in payload.seasons {
            XCTAssertFalse(season.season.isEmpty)
            // The era rule at the payload level: an unavailable season carries no number.
            if season.availability == .unavailable {
                XCTAssertNil(season.value, "\(season.season) is unavailable but still carries a value")
            }
        }
        XCTAssertFalse(CareerArcPayload.preview.seasons.isEmpty)
    }

    // MARK: - The previews are real payloads

    /// Every `preview` is a payload the views render in Xcode, so it has to satisfy the same
    /// invariants a decoded one does — including the em-dash rule.
    func testEveryPreviewPayloadIsWellFormed() throws {
        let encoder = APIClient.makeEncoder()
        for kind in WidgetKind.allCases {
            let payload = WidgetPayload.preview(for: kind)
            XCTAssertEqual(payload.kind, kind)
            // A preview must also round-trip, since the cache stores previews in demo mode.
            let data = try encoder.encode(payload)
            let decoded = try WidgetPayload.decode(kind: kind, from: data, using: decoder)
            XCTAssertEqual(decoded, payload, "\(kind.rawValue).preview did not round-trip")
        }
    }

    func testAnUnavailableMetricValueNeverCarriesANumber() {
        XCTAssertNil(MetricValue.previewUnavailable.value)
        XCTAssertEqual(MetricValue.previewUnavailable.displayValue, Formatting.emDash)
        XCTAssertEqual(MetricValue.previewUnavailable.availability, .unavailable)
        XCTAssertTrue(MetricValue.previewUnavailable.isMissing)
        XCTAssertFalse(MetricValue.preview.isMissing)
    }

    // MARK: - Envelope fixtures

    func testHealthFixture() throws {
        try requireFixtures()
        let response = try decoder.decode(HealthResponse.self, from: try fixture("health"))
        XCTAssertEqual(response.status, "ok")
        XCTAssertTrue(response.isHealthy)
        XCTAssertNotNil(response.syncVersion)
    }

    func testMetaFixtureCarriesBothCatalogs() throws {
        try requireFixtures()
        let response = try decoder.decode(MetaResponse.self, from: try fixture("meta"))
        XCTAssertEqual(response.metrics?.metrics.count, 61)
        XCTAssertEqual(response.widgets?.widgets.count, 12)
        XCTAssertFalse(response.teams.isEmpty)
        XCTAssertFalse(response.seasons.isEmpty)
        XCTAssertEqual(response.coverage?.advancedFrom, "1996-97")
        XCTAssertNotNil(response.attribution)
    }

    func testSyncFixture() throws {
        try requireFixtures()
        let response = try decoder.decode(SyncResponse.self, from: try fixture("sync"))
        XCTAssertGreaterThan(response.syncVersion, 0)
        XCTAssertFalse(response.invalidate.isEmpty)
        // Every kind the server asks the client to drop is one this build knows.
        XCTAssertEqual(response.invalidatedKinds.count, response.invalidate.count,
                       "The fixture names a widget kind this build does not have: \(response.invalidate)")
        for game in response.finalizedGames {
            XCTAssertEqual(game.status, .final)
        }
    }

    func testTeamsFixture() throws {
        try requireFixtures()
        let response = try decoder.decode(TeamsResponse.self, from: try fixture("teams"))
        XCTAssertGreaterThanOrEqual(response.teams.count, 30)
        XCTAssertEqual(Set(response.teams.map { $0.teamId }).count, response.teams.count)
    }

    func testPlayerSearchFixture() throws {
        try requireFixtures()
        let response = try decoder.decode(PlayerSearchResponse.self, from: try fixture("player_search"))
        XCTAssertFalse(response.query.isEmpty)
        XCTAssertFalse(response.results.isEmpty)
        // `PlayerRef` is flattened into each hit alongside the ranking fields.
        for hit in response.results {
            XCTAssertGreaterThan(hit.player.playerId, 0)
            XCTAssertFalse(hit.player.name.isEmpty)
        }
    }

    func testPlayerDetailFixture() throws {
        try requireFixtures()
        let response = try decoder.decode(PlayerDetailResponse.self, from: try fixture("player_detail"))
        XCTAssertGreaterThan(response.player.playerId, 0)
        XCTAssertFalse(response.seasons.isEmpty)
        XCTAssertNotNil(response.bio)
    }

    func testGameLogEndpointFixture() throws {
        try requireFixtures()
        let response = try decoder.decode(GameLogResponse.self, from: try fixture("player_gamelog"))
        XCTAssertFalse(response.rows.isEmpty)
        XCTAssertGreaterThan(response.player.playerId, 0)
    }

    func testScoreboardEndpointFixture() throws {
        try requireFixtures()
        let response = try decoder.decode(ScoreboardResponse.self, from: try fixture("games_scoreboard"))
        XCTAssertFalse(response.games.isEmpty)
    }

    func testLeadersFixtureIsALeaderboardPayload() throws {
        try requireFixtures()
        let payload = try decoder.decode(LeaderboardPayload.self, from: try fixture("leaders"))
        XCTAssertFalse(payload.rows.isEmpty)
        XCTAssertFalse(payload.metric.key.isEmpty)
    }

    func testBoxScoreFixture() throws {
        try requireFixtures()
        let response = try decoder.decode(BoxScoreResponse.self, from: try fixture("game_box"))
        XCTAssertFalse(response.teams.isEmpty)
        XCTAssertFalse(response.game.gameId.isEmpty)
        for team in response.teams {
            XCTAssertFalse(team.players.isEmpty)
        }
    }

    func testTeamDetailFixture() throws {
        try requireFixtures()
        let response = try decoder.decode(TeamDetailResponse.self, from: try fixture("team_detail"))
        XCTAssertFalse(response.team.abbr.isEmpty)
        XCTAssertFalse(response.roster.isEmpty)
    }

    func testErrorEnvelopeFixtures() throws {
        try requireFixtures()
        let notFound = try decoder.decode(ErrorEnvelope.self, from: try fixture("error_not_found"))
        XCTAssertFalse(notFound.error.code.isEmpty)
        XCTAssertFalse(notFound.error.message.isEmpty)
        XCTAssertNotNil(APIError.Code(rawValue: notFound.error.code),
                        "The fixture uses an error code this build does not know: \(notFound.error.code)")

        let invalidConfig = try decoder.decode(ErrorEnvelope.self, from: try fixture("error_invalid_config"))
        XCTAssertEqual(invalidConfig.error.code, APIError.Code.invalidConfig.rawValue)
        XCTAssertNotNil(invalidConfig.error.field, "invalid_config should name the field that failed")
    }

    // MARK: - The resolve envelope

    /// The endpoint the whole dashboard is built on: one response, one typed payload per widget,
    /// each decoded according to its own `kind`.
    func testDashboardResolveFixtureDecodesEveryResult() throws {
        try requireFixtures()
        let response = try decoder.decode(DashboardResolveResponse.self, from: try fixture("dashboard_resolve"))
        XCTAssertFalse(response.results.isEmpty)
        XCTAssertNotNil(response.syncVersion)
        XCTAssertNotNil(response.dataThrough)
        XCTAssertNotNil(response.resolvedContext)

        var kindsSeen: Set<WidgetKind> = []
        for result in response.results {
            XCTAssertFalse(result.widgetId.isEmpty)
            let kind = try XCTUnwrap(result.kind, "Unknown widget kind \"\(result.kindRaw)\"")
            kindsSeen.insert(kind)
            XCTAssertNil(result.decodeError,
                         "\(result.widgetId) (\(result.kindRaw)) did not decode: \(result.decodeError ?? "")")
            switch result.effectiveStatus {
            case .ok, .partial:
                let payload = try XCTUnwrap(result.payload, "\(result.widgetId) has no payload")
                XCTAssertEqual(payload.kind, kind)
            case .unchanged:
                XCTAssertNil(result.payload)
            case .error:
                XCTAssertNotNil(result.failureMessage)
            }
        }
        XCTAssertEqual(kindsSeen, Set(WidgetKind.allCases),
                       "The resolve fixture does not exercise every widget kind")
        XCTAssertEqual(response.resultsByWidgetID.count, response.results.count)
    }

    /// The failure branch of `ResolveResult.init(from:)` — the app's most intricate decoder.
    ///
    /// `contracts/CONTRACT.md` §3 documents a per-widget failure as `status: "error"` with a
    /// populated `error` body and a `null` payload. The resolve fixture carries one on purpose
    /// (`ERROR_WIDGET_CONFIGS` in `nbastats.fixtures_export`: a leaderboard on a metric the era
    /// never recorded, which the service answers with `metric_unavailable`). Without it every
    /// result in every fixture was `ok` or `partial` and this branch had no golden coverage.
    func testDashboardResolveFixtureCarriesAFailedWidget() throws {
        try requireFixtures()
        let response = try decoder.decode(DashboardResolveResponse.self,
                                          from: try fixture("dashboard_resolve"))

        let failures = response.results.filter { $0.effectiveStatus == .error }
        XCTAssertEqual(failures.count, 1,
                       "The resolve fixture must exercise exactly one failed widget")
        let failure = try XCTUnwrap(failures.first)

        XCTAssertNil(failure.payload, "An error result must not carry a payload")
        XCTAssertNil(failure.decodeError, "A well-formed error result is not a decoding failure")
        XCTAssertNotNil(failure.failureMessage)

        let body = try XCTUnwrap(failure.error, "An error result must carry the §7 error body")
        XCTAssertEqual(body.code, APIError.Code.metricUnavailable.rawValue)
        XCTAssertFalse(body.message.isEmpty, "An error body must say something a reader can act on")
        XCTAssertEqual(body.field, "metric")

        // And what the tile becomes: a metric the era never had reads as "unavailable", not as a
        // failure the reader should retry (ARCHITECTURE.md §3 rule 1).
        let error = APIError(body: body, status: 200)
        XCTAssertEqual(error.contractCode, .metricUnavailable)
        XCTAssertFalse(error.userMessage.isEmpty)
    }

    /// The era-honest half of the resolve fixture: results that carry notes, an estimate, or a
    /// stat the season never had.
    func testResolveFixtureCarriesTheEraCases() throws {
        try requireFixtures()
        let response = try decoder.decode(DashboardResolveResponse.self, from: try fixture("dashboard_resolve"))
        let flagged = response.results.filter { ($0.availability ?? .full) != .full }
        XCTAssertFalse(flagged.isEmpty, "The fixture exercises no era caveats at all")
        for result in flagged {
            XCTAssertFalse(result.notes.isEmpty,
                           "\(result.widgetId) is flagged \(result.availability?.rawValue ?? "?") but explains nothing")
        }
        XCTAssertTrue(response.results.contains { $0.availability == .unavailable },
                      "No result in the fixture is era-unavailable")
        XCTAssertTrue(response.results.contains { $0.availability == .estimated },
                      "No result in the fixture is an estimate")
    }

    /// A result whose `kind` this build does not know degrades to one failed tile, and never to a
    /// thrown decode that costs the reader the rest of the dashboard.
    func testAnUnknownKindDegradesToASingleFailedResult() throws {
        let json = """
        {"syncVersion": 1, "dataThrough": "2026-01-02", "results": [
          {"widgetId": "w1", "kind": "stat_tile", "status": "ok", "payload": {
             "subject": {"type": "player", "player": {"playerId": 2544, "name": "LeBron James"}, "team": null},
             "context": "2025-26 · Regular Season · Per Game",
             "primary": {"metric": "ts_pct", "value": 0.6153, "displayValue": "61.5%", "availability": "full"},
             "secondary": [], "sparkline": [], "sparklineMetric": "ts_pct"
           }},
          {"widgetId": "w2", "kind": "teleporter", "status": "ok", "payload": {"anything": true}}
        ]}
        """
        let data = try XCTUnwrap(json.data(using: .utf8))
        let response = try decoder.decode(DashboardResolveResponse.self, from: data)
        XCTAssertEqual(response.results.count, 2)

        let known = try XCTUnwrap(response.resultsByWidgetID["w1"])
        XCTAssertEqual(known.kind, .statTile)
        XCTAssertNotNil(known.payload)
        XCTAssertNil(known.decodeError)

        let unknown = try XCTUnwrap(response.resultsByWidgetID["w2"])
        XCTAssertNil(unknown.kind)
        XCTAssertNil(unknown.payload)
        XCTAssertEqual(unknown.effectiveStatus, .error)
        XCTAssertNotNil(unknown.failureMessage)
        XCTAssertTrue(unknown.failureMessage?.contains("teleporter") ?? false, "\(unknown.failureMessage ?? "")")
    }

    func testAPayloadThatCannotBeReadDegradesToOneFailedResult() throws {
        let json = """
        {"results": [
          {"widgetId": "w1", "kind": "leaderboard", "status": "ok", "payload": {"rows": "not an array"}}
        ]}
        """
        let data = try XCTUnwrap(json.data(using: .utf8))
        let response = try decoder.decode(DashboardResolveResponse.self, from: data)
        let result = try XCTUnwrap(response.results.first)
        XCTAssertNil(result.payload)
        XCTAssertEqual(result.effectiveStatus, .error)
        XCTAssertNotNil(result.decodeError)
    }
}
