import Foundation
import XCTest
@testable import Hardwood

/// `next_game_projection` — the payload, and the honesty rules that are properties of the data
/// rather than of the view (`contracts/CONTRACT.md` §4, `docs/PROJECTION.md` §7).
///
/// The golden fixture is generated by the backend out of a real resolver, so it may not exist
/// yet. Every test here therefore asserts the same invariants against
/// `NextGameProjectionPayload.preview` — the value three Xcode previews render — before it looks
/// for the fixture, and skips with the command that produces one rather than passing vacuously.
final class ProjectionPayloadTests: XCTestCase {

    private let decoder = APIClient.makeDecoder()

    /// The fixture the contract promises, named for the widget kind like every other one.
    private static let fixtureName = "widget_\(WidgetKind.nextGameProjection.rawValue)"

    // MARK: - The shared invariants

    /// Everything that must be true of *any* projection, whoever built it.
    private func assertProjectionInvariants(_ payload: NextGameProjectionPayload,
                                            _ source: String,
                                            file: StaticString = #filePath,
                                            line: UInt = #line) {
        XCTAssertGreaterThan(payload.player.playerId, 0, "\(source): the projection names no player",
                             file: file, line: line)
        XCTAssertFalse(payload.lines.isEmpty, "\(source): a projection with no lines projects nothing",
                       file: file, line: line)

        for projected in payload.lines {
            let label = "\(source) · \(projected.metric)"

            // §7 rule 5. A projection is never a record, so it can never be `.full`: that is the
            // one value that renders with no dashed underline and no "est." marker.
            XCTAssertEqual(projected.availability, .estimated, "\(label) is not marked estimated",
                           file: file, line: line)
            XCTAssertNotEqual(projected.availability, .full, "\(label) claims to be a measured record",
                              file: file, line: line)
            XCTAssertFalse(projected.displayValue.isEmpty, "\(label) has no rendered value",
                           file: file, line: line)

            // §7 rule 1. The mean sits inside its own interval, whenever the bounds are there.
            //
            // With one exception, and it is a property of the distribution rather than a licence:
            // these are *quantile* intervals over a count, so a tiny mean can fall outside a
            // degenerate one. The shipped fixture projects 0.08 three-pointers with an 80%
            // interval of 0–0, because he makes none more than 90% of the time — true, and not
            // the same thing as a mean that contradicts its interval. A collapsed interval is
            // therefore only required to sit within one whole count of the mean; every other
            // interval must contain it outright.
            if let low = projected.low, let high = projected.high {
                XCTAssertTrue(low.isFinite && high.isFinite, "\(label) has a non-finite bound",
                              file: file, line: line)
                XCTAssertLessThanOrEqual(low, high, "\(label): low is above high", file: file, line: line)
                if let mean = projected.mean {
                    if low == high {
                        XCTAssertLessThanOrEqual(abs(mean - low), 1,
                                                 "\(label): the interval collapsed to \(low) but the mean is \(mean)",
                                                 file: file, line: line)
                    } else {
                        XCTAssertLessThanOrEqual(low, mean, "\(label): the mean is below its own interval",
                                                 file: file, line: line)
                        XCTAssertLessThanOrEqual(mean, high, "\(label): the mean is above its own interval",
                                                 file: file, line: line)
                    }
                }
                XCTAssertNotEqual(projected.intervalText, Formatting.emDash,
                                  "\(label) has bounds but renders no range", file: file, line: line)
            } else {
                // A line with no interval says so; it must never render as a bare confident number.
                XCTAssertEqual(projected.intervalText, Formatting.emDash,
                               "\(label) renders a range it does not have", file: file, line: line)
            }

            // A nominal coverage is a probability: strictly inside (0, 1), never 80 for "80%".
            if let level = projected.intervalLevel {
                XCTAssertTrue(level.isFinite, "\(label): interval level is not a number", file: file, line: line)
                XCTAssertGreaterThan(level, 0, "\(label): interval level \(level) is not a probability",
                                     file: file, line: line)
                XCTAssertLessThan(level, 1, "\(label): interval level \(level) is not a probability",
                                  file: file, line: line)
            }

            // `w = n / (n + k)` is a weight, and exposure is a duration.
            if let weight = projected.shrinkageWeight {
                XCTAssertGreaterThanOrEqual(weight, 0, "\(label): negative shrinkage weight", file: file, line: line)
                XCTAssertLessThanOrEqual(weight, 1, "\(label): shrinkage weight above 1", file: file, line: line)
            }
            if let exposure = projected.exposureMinutes {
                XCTAssertGreaterThanOrEqual(exposure, 0, "\(label): negative exposure", file: file, line: line)
            }
            if let multiplier = projected.dispersionMultiplier {
                XCTAssertGreaterThan(multiplier, 0, "\(label): a variance multiplier cannot be zero or negative",
                                     file: file, line: line)
            }
        }

        // §7 rule 2. The minutes are the dominant error term and carry their own interval.
        let minutes = payload.projectedMinutes
        if let low = minutes.low, let high = minutes.high {
            XCTAssertLessThanOrEqual(low, high, "\(source): the minutes interval is inverted",
                                     file: file, line: line)
            if let value = minutes.value {
                XCTAssertLessThanOrEqual(low, value, "\(source): projected minutes are below their interval",
                                         file: file, line: line)
                XCTAssertLessThanOrEqual(value, high, "\(source): projected minutes are above their interval",
                                         file: file, line: line)
            }
        }

        // §7 rule 3. A context factor is a multiplier around 1.0, not a percentage.
        for factor in payload.factors {
            guard let value = factor.value else { continue }
            XCTAssertTrue(value.isFinite, "\(source) · \(factor.key): factor is not a number", file: file, line: line)
            XCTAssertGreaterThan(value, 0, "\(source) · \(factor.key): a multiplier cannot be zero or negative",
                                 file: file, line: line)
            XCTAssertLessThan(abs(value - 1), 0.5,
                              "\(source) · \(factor.key): \(value) is not normalised around 1.0",
                              file: file, line: line)
        }

        if let combo = payload.combo {
            assertComboInvariants(combo,
                                  correlationApplied: payload.method.correlationApplied,
                                  source: source,
                                  file: file,
                                  line: line)
        }
    }

    /// §5 of the derivation: the residuals are positively dependent, so the correlated spread is
    /// wider than the independent one, and the matrix behind it has to be a correlation matrix.
    private func assertComboInvariants(_ combo: ProjectionCombo,
                                       correlationApplied: Bool,
                                       source: String,
                                       file: StaticString = #filePath,
                                       line: UInt = #line) {
        if let low = combo.low, let high = combo.high {
            XCTAssertLessThanOrEqual(low, high, "\(source): the combined interval is inverted",
                                     file: file, line: line)
            if let mean = combo.mean {
                XCTAssertLessThanOrEqual(low, mean, "\(source): the combined mean is below its interval",
                                         file: file, line: line)
                XCTAssertLessThanOrEqual(mean, high, "\(source): the combined mean is above its interval",
                                         file: file, line: line)
            }
        }

        if let sd = combo.sd, let independent = combo.sdIfIndependent {
            XCTAssertGreaterThan(sd, 0, "\(source): a standard deviation cannot be zero", file: file, line: line)
            XCTAssertGreaterThan(independent, 0, "\(source): a standard deviation cannot be zero",
                                 file: file, line: line)
            if correlationApplied {
                // Ignoring the covariance understates the spread — held out, by 12.8%.
                XCTAssertGreaterThan(sd, independent,
                                     "\(source): the correlated spread is not wider than the independent one",
                                     file: file, line: line)
            }
            if let inflation = combo.inflation {
                XCTAssertEqual(inflation, sd / independent - 1, accuracy: 0.005,
                               "\(source): inflation does not match the two spreads", file: file, line: line)
            }
        }

        let matrix = combo.correlation
        guard !matrix.isEmpty else { return }
        for row in matrix {
            XCTAssertEqual(row.count, matrix.count, "\(source): the correlation matrix is not square",
                           file: file, line: line)
        }
        guard matrix.allSatisfy({ $0.count == matrix.count }) else { return }
        for i in matrix.indices {
            XCTAssertEqual(matrix[i][i], 1, accuracy: 1e-9,
                           "\(source): correlation diagonal [\(i)][\(i)] is not 1", file: file, line: line)
            for j in matrix.indices {
                XCTAssertEqual(matrix[i][j], matrix[j][i], accuracy: 1e-9,
                               "\(source): the correlation matrix is not symmetric at [\(i)][\(j)]",
                               file: file, line: line)
                XCTAssertGreaterThanOrEqual(matrix[i][j], -1, "\(source): correlation below -1",
                                            file: file, line: line)
                XCTAssertLessThanOrEqual(matrix[i][j], 1, "\(source): correlation above 1",
                                         file: file, line: line)
            }
        }
    }

    // MARK: - The fixture

    func testFixtureDecodesAndSatisfiesTheInvariants() throws {
        // Asserted first and unconditionally, so this test is never a no-op.
        assertProjectionInvariants(.preview, "preview")

        guard let data = TestBundles.fixtureData(named: ProjectionPayloadTests.fixtureName) else {
            throw XCTSkip("""
                \(ProjectionPayloadTests.fixtureName).json is not in any test-visible bundle, so \
                only the preview payload was checked. The fixtures are generated from the running \
                service — `python3 -m nbastats.fixtures_export --out ../contracts/fixtures`, which \
                needs a next_game_projection resolver in backend/nbastats/widgets/ — and copied \
                into the test bundle by scripts/sync_contracts.sh.
                """)
        }

        let payload = try decoder.decode(NextGameProjectionPayload.self, from: data)
        assertProjectionInvariants(payload, "fixture")

        // The fixture is the contract's own example, so it carries the parts the contract shows.
        XCTAssertFalse(payload.factors.isEmpty, "The fixture shows no context factors (§7 rule 3)")
        XCTAssertFalse(payload.notes.isEmpty, "The fixture carries no notes")
        XCTAssertNotNil(payload.projectedMinutes.value, "The fixture projects no minutes (§7 rule 2)")

        // And it decodes through the umbrella the resolve response uses, into the right case.
        let wrapped = try WidgetPayload.decode(kind: .nextGameProjection, from: data, using: decoder)
        XCTAssertEqual(wrapped.kind, .nextGameProjection)
        guard case .nextGameProjection(let unwrapped) = wrapped else {
            return XCTFail("The fixture decoded into the wrong payload case")
        }
        XCTAssertEqual(unwrapped, payload)
    }

    func testFixtureSurvivesTheDiskCacheRoundTrip() throws {
        let encoder = APIClient.makeEncoder()
        let previewData = try encoder.encode(NextGameProjectionPayload.preview)
        XCTAssertEqual(try decoder.decode(NextGameProjectionPayload.self, from: previewData),
                       NextGameProjectionPayload.preview,
                       "The preview projection changed on the way through the cache")

        guard let data = TestBundles.fixtureData(named: ProjectionPayloadTests.fixtureName) else {
            throw XCTSkip("""
                \(ProjectionPayloadTests.fixtureName).json is not in any test-visible bundle; only \
                the preview payload was round-tripped. Generate the fixtures with \
                `python3 -m nbastats.fixtures_export` and copy them in with \
                scripts/sync_contracts.sh.
                """)
        }
        let payload = try decoder.decode(NextGameProjectionPayload.self, from: data)
        let again = try decoder.decode(NextGameProjectionPayload.self, from: try encoder.encode(payload))
        XCTAssertEqual(again, payload, "The fixture changed on the way through the cache")
    }

    // MARK: - The preview, in its own right

    func testPreviewCombinedLineShowsWhatIgnoringCorrelationWouldClaim() throws {
        let combo = try XCTUnwrap(NextGameProjectionPayload.preview.combo)
        let sd = try XCTUnwrap(combo.sd)
        let independent = try XCTUnwrap(combo.sdIfIndependent)
        XCTAssertEqual(combo.label, "PTS+REB+AST")
        XCTAssertEqual(sd, 9.21, accuracy: 1e-9)
        XCTAssertEqual(independent, 8.17, accuracy: 1e-9)
        XCTAssertGreaterThan(sd, independent)
        XCTAssertFormatted(combo.inflationText, "+12.7%")
        XCTAssertEqual(combo.correlation.count, 3)
        XCTAssertTrue(NextGameProjectionPayload.preview.method.correlationApplied)
    }

    func testPreviewCarriesEveryContextFactorTheFormulaHas() {
        let payload = NextGameProjectionPayload.preview
        for key in ["pace", "opponent", "home", "rest"] {
            XCTAssertNotNil(payload.factor(key), "No \(key) factor, which §7 rule 3 requires")
        }
        XCTAssertNotNil(payload.line("pts"))
        XCTAssertNil(payload.line("no_such_metric"))
        XCTAssertFalse(payload.hasThinExposure, "The preview is the well-supported case")
    }

    func testAFactorRendersItsEffectAsASignedPercentage() {
        XCTAssertFormatted(ProjectionFactor(key: "pace", label: "Pace", value: 1.021).effectText, "+2.1%")
        XCTAssertFormatted(ProjectionFactor(key: "opponent", label: "Opponent", value: 0.981).effectText, "-1.9%")
        XCTAssertEqual(ProjectionFactor(key: "rest", label: "Rest").effectText, Formatting.emDash)
        XCTAssertTrue(ProjectionFactor(key: "home", label: "Home", value: 1.0).isNeutral)
        XCTAssertTrue(ProjectionFactor(key: "home", label: "Home", value: nil).isNeutral,
                      "A factor with no value cannot be claimed to move anything")
    }

    // MARK: - A projection is never a record

    func testAServerThatCallsALineFullStillRendersAsAnEstimate() throws {
        let json = """
        {"metric": "pts", "mean": 28.4, "displayValue": "28.4",
         "low": 19, "high": 38, "intervalLevel": 0.8, "availability": "full"}
        """
        let line = try decoder.decode(ProjectedLine.self, from: Data(json.utf8))
        XCTAssertEqual(line.availability, .estimated,
                       "A projected line decoded as a measured record, which §7 rule 5 forbids")
    }

    func testALineBuiltInCodeCannotClaimToBeFull() {
        let line = ProjectedLine(metric: "pts", displayValue: "28.4", availability: .full)
        XCTAssertEqual(line.availability, .estimated)
        XCTAssertEqual(ProjectedLine(metric: "pts", displayValue: "28.4").availability, .estimated,
                       "The default availability of a projected line is not estimated")
    }

    func testAnUnreadableAvailabilityIsNeverResolvedUpward() throws {
        let json = #"{"metric": "pts", "displayValue": "28.4", "availability": "sort-of"}"#
        let line = try decoder.decode(ProjectedLine.self, from: Data(json.utf8))
        XCTAssertNotEqual(line.availability, .full,
                          "An availability this build cannot read became a confident number")
    }

    func testAMissingAvailabilityKeyIsEstimated() throws {
        let json = #"{"metric": "reb", "mean": 7.8, "displayValue": "7.8"}"#
        let line = try decoder.decode(ProjectedLine.self, from: Data(json.utf8))
        XCTAssertEqual(line.availability, .estimated)
    }

    // MARK: - Decoding tolerances the contract needs

    func testAWholeNumberWrittenAsADecimalStillDecodes() throws {
        let json = """
        {"metric": "reb", "displayValue": "7.8", "halfLifeGames": 8.0, "shrinkageK": 34}
        """
        let line = try decoder.decode(ProjectedLine.self, from: Data(json.utf8))
        XCTAssertEqual(line.halfLifeGames, 8, "A serialiser writing 8.0 cost the line its half-life")
        XCTAssertEqual(line.shrinkageK ?? 0, 34, accuracy: 1e-9)

        let method = try decoder.decode(ProjectionMethod.self,
                                        from: Data(#"{"minutesHalfLifeGames": 2.0}"#.utf8))
        XCTAssertEqual(method.minutesHalfLifeGames, 2)
        XCTAssertFalse(method.correlationApplied,
                       "An absent correlationApplied must read as false, the cautious direction")
    }

    func testADescriptorThisBuildCannotReadCostsOneLineItsFormattingAndNothingElse() throws {
        let json = """
        {"metric": "pts", "mean": 28.4, "displayValue": "28.4",
         "descriptor": {"key": "pts", "name": "Points"},
         "availability": "estimated"}
        """
        let line = try decoder.decode(ProjectedLine.self, from: Data(json.utf8))
        XCTAssertNil(line.descriptor, "A half-written descriptor should be dropped, not thrown")
        XCTAssertEqual(line.displayValue, "28.4")
        XCTAssertEqual(line.shortName, "PTS", "With no descriptor the metric key stands in")
    }

    // MARK: - Degrading honestly

    func testAPlayerWithNoScheduledGameStillProjects() throws {
        let json = """
        {"player": {"playerId": 1642300, "name": "Rookie Guard"},
         "game": null,
         "projectedMinutes": {"value": 11.4, "displayValue": "11.4"},
         "lines": [{"metric": "pts", "mean": 4.6, "displayValue": "4.6",
                    "shrinkageWeight": 0.16, "exposureMinutes": 63, "shrinkageK": 81,
                    "availability": "estimated"}],
         "factors": [{"key": "pace", "label": "Pace", "value": 1.0}],
         "method": {"correlationApplied": false},
         "notes": ["Projected against a league-average opponent."]}
        """
        let payload = try decoder.decode(NextGameProjectionPayload.self, from: Data(json.utf8))
        XCTAssertNil(payload.game, "A payload with no scheduled game should decode, not throw")
        XCTAssertNil(payload.combo)
        XCTAssertFalse(payload.notes.isEmpty, "The reader is never told why there is no opponent")
        XCTAssertTrue(payload.hasThinExposure,
                      "A rate that is 16% player and 84% league prior is not a confident number")
        let line = try XCTUnwrap(payload.line("pts"))
        XCTAssertTrue(line.leansOnLeaguePrior)
        XCTAssertEqual(line.intervalText, Formatting.emDash,
                       "A line with no bounds must render an em dash, never a bare mean")
        assertProjectionInvariants(payload, "thin history")
    }

    func testAnEmptyPayloadDecodesToItsEmptyDefaultsRatherThanThrowing() throws {
        let json = #"{"player": {"playerId": 2544, "name": "LeBron James"}}"#
        let payload = try decoder.decode(NextGameProjectionPayload.self, from: Data(json.utf8))
        XCTAssertTrue(payload.lines.isEmpty)
        XCTAssertTrue(payload.factors.isEmpty)
        XCTAssertTrue(payload.notes.isEmpty)
        XCTAssertNil(payload.game)
        XCTAssertNil(payload.combo)
        XCTAssertEqual(payload.projectedMinutes.displayValue, Formatting.emDash,
                       "Absent minutes must render an em dash, never 0")
        XCTAssertFalse(payload.method.correlationApplied)
    }

    // MARK: - Interval rendering

    func testAnIntervalOnACountingStatRendersAsWholeNumbers() throws {
        let line = ProjectedLine(metric: "pts",
                                 descriptor: nil,
                                 mean: 28.4,
                                 displayValue: "28.4",
                                 low: 19,
                                 high: 38,
                                 intervalLevel: 0.8)
        XCTAssertFormatted(line.intervalText, "19–38")
        XCTAssertFormatted(try XCTUnwrap(line.intervalLevelText), "80% interval")
        XCTAssertNil(ProjectedLine(metric: "pts", intervalLevel: nil).intervalLevelText)
    }

    func testProjectedMinutesRenderTheirOwnRangeToOneDecimal() {
        XCTAssertFormatted(ProjectedMinutes.preview.intervalText, "27.0–40.5")
        XCTAssertEqual(ProjectedMinutes().intervalText, Formatting.emDash)
        XCTAssertEqual(ProjectedMinutes.preview.deltaFromSeasonAverage ?? 0, 0.4, accuracy: 1e-9)
        XCTAssertNil(ProjectedMinutes(value: 34.2).deltaFromSeasonAverage)
    }

    func testTheProjectionGameSpellsOutTheMatchupAndTheRest() {
        XCTAssertEqual(ProjectionGame.preview.matchupText, "vs BOS")
        XCTAssertEqual(ProjectionGame.preview.restText, "2 days rest")
        XCTAssertEqual(ProjectionGame(gameId: "1", opponentAbbr: "BOS", isHome: false).matchupText, "@ BOS")
        XCTAssertEqual(ProjectionGame(gameId: "1", restDays: 1).restText, "1 day rest")
        XCTAssertEqual(ProjectionGame(gameId: "1", restDays: 0, isBackToBack: true).restText, "Back-to-back")
        XCTAssertEqual(ProjectionGame(gameId: "1").restText, Formatting.emDash)
        XCTAssertEqual(ProjectionGame(gameId: "1").matchupText, Formatting.emDash)
    }
}
