"""``GET /v1/health``, ``GET /v1/meta`` and ``GET /v1/presets``.

These three are what the app calls before it can draw anything: health for the launch gate,
meta for league state plus the three catalogs (so a catalog change reaches clients without an
App Store release), and presets for the nine starter dashboards.

``/v1/health`` is the one route that never requires an API key and never touches the request
session dependency: it opens its own session inside a ``try`` so that a database that is down
answers ``503`` with a readable body instead of a stack trace.
"""
from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, Response
from sqlalchemy import func, select

from .. import API_VERSION, SCHEMA_VERSION, catalog
from ..config import get_settings
from ..db import get_sessionmaker
from ..models import Game, SyncState, Team
from .deps import SessionDep, current_season
from .schemas import (
    Coverage,
    HealthResponse,
    MetaResponse,
    PresetsResponse,
    SeasonInfo,
    SubjectTokenInfo,
)
from .serializers import team_ref

__all__ = ["router", "ATTRIBUTION", "DEMO_ATTRIBUTION", "presets_version"]

logger = logging.getLogger("nbastats.api")

router = APIRouter()

#: Required wherever NBA.com data is shown.
ATTRIBUTION = "Stats via NBA.com. Not endorsed by or affiliated with the NBA."

#: What a demo server says instead. The seeded league is invented; crediting NBA.com for it
#: would be a lie the client would repeat in its footer.
DEMO_ATTRIBUTION = (
    "Demo data: a synthetic league generated by nbastats.seed. Not NBA data, and not "
    "endorsed by or affiliated with the NBA."
)

#: First season with per-game advanced box scores, plus/minus and shot charts.
ADVANCED_FROM = "1996-97"


def presets_version() -> int:
    """The preset catalog's content version.

    ``contracts/presets.json`` carries a ``version`` counter that
    ``contracts/tools/gen_presets.py`` bumps in the same commit that edits the presets, so this
    increments the way ``contracts/CONTRACT.md`` §3 promises: a client stores the last version
    it saw and tests ``server > mine`` to offer "this preset was updated". A fingerprint would
    not support that test — it can decrease, and it can collide.
    """
    raw = catalog.presets_document().get("version")
    if isinstance(raw, int) and not isinstance(raw, bool) and raw >= 0:
        return raw
    return 0


def _has_synthetic_data(session: Any) -> bool:
    """True when the store holds seeded demo rows rather than ingested ones."""
    found = session.execute(
        select(Game.game_id).where(Game.data_source == "synthetic").limit(1)
    ).first()
    return found is not None


@router.get(
    "/health",
    response_model=HealthResponse,
    summary="Liveness and data freshness",
    responses={503: {"description": "The database is not ready."}},
)
def health(response: Response) -> HealthResponse:
    """Liveness plus the freshness cursor. Never requires an API key.

    ``200`` when the store answers, ``503`` with the same body when it does not — a load
    balancer reads the status, a human reads ``databaseReady``.
    """
    settings = get_settings()
    sync_version = 0
    data_through = None
    demo = settings.demo_mode
    ready = False
    try:
        with get_sessionmaker()() as session:
            state = session.execute(
                select(SyncState).where(SyncState.id == 1)
            ).scalar_one_or_none()
            if state is not None:
                sync_version = state.sync_version or 0
                data_through = state.data_through
            session.execute(select(func.count()).select_from(Team)).scalar_one()
            demo = demo or _has_synthetic_data(session)
            ready = True
    except Exception:  # pragma: no cover - exercised only when the store is broken
        logger.exception("health check could not read the database")

    if not ready:
        response.status_code = 503
    return HealthResponse(
        status="ok" if ready else "degraded",
        version=API_VERSION,
        sync_version=sync_version,
        data_through=data_through,
        database_ready=ready,
        seeded_demo_data=demo,
    )


@router.get("/meta", response_model=MetaResponse, summary="League state and the catalogs")
def meta(session: SessionDep) -> MetaResponse:
    """Everything the client caches for 24 hours: league state plus the three catalogs."""
    state = session.execute(select(SyncState).where(SyncState.id == 1)).scalar_one_or_none()
    season_now = current_season(session)

    counted = session.execute(
        select(Game.season, Game.season_type, func.count(Game.game_id)).group_by(
            Game.season, Game.season_type
        )
    ).all()
    by_season: dict[str, dict[str, Any]] = {}
    for season, season_type, count in counted:
        entry = by_season.setdefault(season, {"types": [], "count": 0})
        if season_type not in entry["types"]:
            entry["types"].append(season_type)
        entry["count"] += int(count)

    seasons = [
        SeasonInfo(
            season=season,
            season_types=sorted(entry["types"]),
            is_current=season == season_now,
            has_advanced=catalog.season_sort_key(season)
            >= catalog.season_sort_key(ADVANCED_FROM),
            game_count=entry["count"],
        )
        for season, entry in sorted(
            by_season.items(), key=lambda item: catalog.season_sort_key(item[0]), reverse=True
        )
    ]

    teams = session.execute(select(Team).order_by(Team.abbr)).scalars().all()
    demo = get_settings().demo_mode or _has_synthetic_data(session)

    return MetaResponse(
        sync_version=(state.sync_version or 0) if state is not None else 0,
        data_through=state.data_through if state is not None else None,
        current_season=season_now,
        seasons=seasons,
        metrics=catalog.metrics_document(),
        widgets=catalog.widgets_document(),
        teams=[team_ref(team) for team in teams],
        coverage=Coverage.model_validate(catalog.coverage()),
        attribution=DEMO_ATTRIBUTION if demo else ATTRIBUTION,
    )


@router.get("/presets", response_model=PresetsResponse, summary="The preset dashboards")
def presets() -> PresetsResponse:
    """The nine preset dashboards, exactly as ``contracts/presets.json`` holds them."""
    document = catalog.presets_document()
    return PresetsResponse(
        schema_version=int(document.get("schemaVersion", SCHEMA_VERSION)),
        version=presets_version(),
        presets=list(document.get("presets", [])),
        subject_tokens=[
            SubjectTokenInfo.model_validate(token)
            for token in document.get("subjectTokens", [])
        ],
    )
