-- Hardwood schema, generated by nbastats.models.render_schema_sql().
-- Do not edit by hand: run `python3 -m nbastats.models > nbastats/schema.sql`.
-- Dialect: SQLite. A Postgres DATABASE_URL works from the same models without
-- code changes; run init_db() there rather than this file.

CREATE TABLE id_crosswalk (
	nba_person_id INTEGER NOT NULL, 
	bbref_slug VARCHAR(16), 
	espn_id INTEGER, 
	balldontlie_id INTEGER, 
	confidence FLOAT, 
	method VARCHAR(32), 
	PRIMARY KEY (nba_person_id)
);

CREATE INDEX ix_id_crosswalk_bbref_slug ON id_crosswalk (bbref_slug);

CREATE TABLE ingest_log (
	id INTEGER NOT NULL, 
	started_at DATETIME, 
	finished_at DATETIME, 
	job VARCHAR(32) NOT NULL, 
	season VARCHAR(8), 
	status VARCHAR(16) NOT NULL, 
	games_written INTEGER NOT NULL, 
	rows_written INTEGER NOT NULL, 
	error TEXT, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_ingest_log_started ON ingest_log (started_at);

CREATE TABLE league_season (
	subject_type VARCHAR(8) NOT NULL, 
	season VARCHAR(8) NOT NULL, 
	season_type VARCHAR(16) NOT NULL, 
	metric_key VARCHAR(32) NOT NULL, 
	sample_size INTEGER, 
	average FLOAT, 
	stddev FLOAT, 
	p10 FLOAT, 
	p25 FLOAT, 
	p50 FLOAT, 
	p75 FLOAT, 
	p90 FLOAT, 
	min_value FLOAT, 
	max_value FLOAT, 
	PRIMARY KEY (subject_type, season, season_type, metric_key)
);

CREATE TABLE players (
	player_id INTEGER NOT NULL, 
	full_name VARCHAR(96) NOT NULL, 
	first_name VARCHAR(48), 
	last_name VARCHAR(48), 
	bbref_slug VARCHAR(16), 
	position VARCHAR(8), 
	height VARCHAR(8), 
	weight INTEGER, 
	birthdate DATE, 
	country VARCHAR(48), 
	school VARCHAR(96), 
	draft_year INTEGER, 
	draft_round INTEGER, 
	draft_pick INTEGER, 
	from_year INTEGER, 
	to_year INTEGER, 
	is_active BOOLEAN NOT NULL, 
	jersey VARCHAR(8), 
	headshot_url VARCHAR(255), 
	PRIMARY KEY (player_id)
);

CREATE INDEX ix_players_bbref_slug ON players (bbref_slug);
CREATE INDEX ix_players_full_name ON players (full_name);
CREATE INDEX ix_players_is_active ON players (is_active);
CREATE INDEX ix_players_last_name ON players (last_name);

CREATE TABLE shot_zone_season (
	subject_type VARCHAR(8) NOT NULL, 
	subject_id INTEGER NOT NULL, 
	season VARCHAR(8) NOT NULL, 
	season_type VARCHAR(16) NOT NULL, 
	zone VARCHAR(24) NOT NULL, 
	fga FLOAT, 
	fgm FLOAT, 
	fga_tot INTEGER, 
	fgm_tot INTEGER, 
	fg_pct FLOAT, 
	share_of_fga FLOAT, 
	points_per_shot FLOAT, 
	PRIMARY KEY (subject_type, subject_id, season, season_type, zone)
);

CREATE INDEX ix_shot_zone_subject ON shot_zone_season (subject_type, subject_id, season);

CREATE TABLE sync_state (
	id INTEGER NOT NULL, 
	sync_version INTEGER NOT NULL, 
	data_through DATE, 
	last_run_at DATETIME, 
	last_success_at DATETIME, 
	games_ingested INTEGER NOT NULL, 
	notes TEXT, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_sync_state_singleton CHECK (id = 1)
);

CREATE TABLE teams (
	team_id INTEGER NOT NULL, 
	abbr VARCHAR(8) NOT NULL, 
	name VARCHAR(64) NOT NULL, 
	city VARCHAR(64) NOT NULL, 
	nickname VARCHAR(64) NOT NULL, 
	conference VARCHAR(8), 
	division VARCHAR(16), 
	is_active BOOLEAN NOT NULL, 
	year_founded INTEGER, 
	year_last_active INTEGER, 
	PRIMARY KEY (team_id)
);

CREATE INDEX ix_teams_abbr ON teams (abbr);

CREATE TABLE games (
	game_id VARCHAR(16) NOT NULL, 
	game_date DATE NOT NULL, 
	season VARCHAR(8) NOT NULL, 
	season_type VARCHAR(16) NOT NULL, 
	home_team_id INTEGER NOT NULL, 
	away_team_id INTEGER NOT NULL, 
	home_pts INTEGER, 
	away_pts INTEGER, 
	status VARCHAR(12) NOT NULL, 
	period INTEGER, 
	clock VARCHAR(8), 
	finalized_at DATETIME, 
	data_source VARCHAR(16), 
	ingested_at DATETIME, 
	PRIMARY KEY (game_id), 
	FOREIGN KEY(home_team_id) REFERENCES teams (team_id), 
	FOREIGN KEY(away_team_id) REFERENCES teams (team_id)
);

CREATE INDEX ix_games_away_team ON games (away_team_id, game_date);
CREATE INDEX ix_games_game_date ON games (game_date);
CREATE INDEX ix_games_home_team ON games (home_team_id, game_date);
CREATE INDEX ix_games_season_type ON games (season, season_type);

CREATE TABLE player_season (
	player_id INTEGER NOT NULL, 
	season VARCHAR(8) NOT NULL, 
	season_type VARCHAR(16) NOT NULL, 
	team_id INTEGER NOT NULL, 
	age INTEGER, 
	gp INTEGER, 
	gs INTEGER, 
	minutes FLOAT, 
	min_pg FLOAT, 
	pts FLOAT, 
	reb FLOAT, 
	oreb FLOAT, 
	dreb FLOAT, 
	ast FLOAT, 
	stl FLOAT, 
	blk FLOAT, 
	tov FLOAT, 
	pf FLOAT, 
	fgm FLOAT, 
	fga FLOAT, 
	fg3m FLOAT, 
	fg3a FLOAT, 
	ftm FLOAT, 
	fta FLOAT, 
	plus_minus FLOAT, 
	fantasy_pts FLOAT, 
	game_score FLOAT, 
	pts_tot INTEGER, 
	reb_tot INTEGER, 
	oreb_tot INTEGER, 
	dreb_tot INTEGER, 
	ast_tot INTEGER, 
	stl_tot INTEGER, 
	blk_tot INTEGER, 
	tov_tot INTEGER, 
	pf_tot INTEGER, 
	fgm_tot INTEGER, 
	fga_tot INTEGER, 
	fg3m_tot INTEGER, 
	fg3a_tot INTEGER, 
	ftm_tot INTEGER, 
	fta_tot INTEGER, 
	plus_minus_tot FLOAT, 
	fantasy_pts_tot FLOAT, 
	fg_pct FLOAT, 
	fg3_pct FLOAT, 
	ft_pct FLOAT, 
	efg_pct FLOAT, 
	ts_pct FLOAT, 
	fg3a_rate FLOAT, 
	ftr FLOAT, 
	pps FLOAT, 
	off_rtg FLOAT, 
	def_rtg FLOAT, 
	net_rtg FLOAT, 
	usg_pct FLOAT, 
	ast_pct FLOAT, 
	ast_tov FLOAT, 
	ast_ratio FLOAT, 
	oreb_pct FLOAT, 
	dreb_pct FLOAT, 
	reb_pct FLOAT, 
	tov_pct FLOAT, 
	stl_pct FLOAT, 
	blk_pct FLOAT, 
	pace FLOAT, 
	poss FLOAT, 
	pie FLOAT, 
	per FLOAT, 
	ws FLOAT, 
	ows FLOAT, 
	dws FLOAT, 
	ws48 FLOAT, 
	bpm FLOAT, 
	obpm FLOAT, 
	dbpm FLOAT, 
	vorp FLOAT, 
	is_estimated BOOLEAN NOT NULL, 
	data_source VARCHAR(16), 
	PRIMARY KEY (player_id, season, season_type, team_id), 
	FOREIGN KEY(player_id) REFERENCES players (player_id), 
	FOREIGN KEY(team_id) REFERENCES teams (team_id)
);

CREATE INDEX ix_player_season_player ON player_season (player_id, season, season_type);
CREATE INDEX ix_player_season_season ON player_season (season, season_type);
CREATE INDEX ix_player_season_team ON player_season (team_id, season, season_type);

CREATE TABLE team_season (
	team_id INTEGER NOT NULL, 
	season VARCHAR(8) NOT NULL, 
	season_type VARCHAR(16) NOT NULL, 
	gp INTEGER, 
	wins INTEGER, 
	losses INTEGER, 
	win_pct FLOAT, 
	pts FLOAT, 
	opp_pts FLOAT, 
	reb FLOAT, 
	oreb FLOAT, 
	dreb FLOAT, 
	ast FLOAT, 
	stl FLOAT, 
	blk FLOAT, 
	tov FLOAT, 
	pf FLOAT, 
	fgm FLOAT, 
	fga FLOAT, 
	fg3m FLOAT, 
	fg3a FLOAT, 
	ftm FLOAT, 
	fta FLOAT, 
	min_pg FLOAT, 
	pts_tot INTEGER, 
	reb_tot INTEGER, 
	ast_tot INTEGER, 
	fgm_tot INTEGER, 
	fga_tot INTEGER, 
	fg3m_tot INTEGER, 
	fg3a_tot INTEGER, 
	ftm_tot INTEGER, 
	fta_tot INTEGER, 
	minutes FLOAT, 
	fg_pct FLOAT, 
	fg3_pct FLOAT, 
	ft_pct FLOAT, 
	efg_pct FLOAT, 
	ts_pct FLOAT, 
	fg3a_rate FLOAT, 
	ftr FLOAT, 
	pps FLOAT, 
	tov_pct FLOAT, 
	oreb_pct FLOAT, 
	dreb_pct FLOAT, 
	reb_pct FLOAT, 
	opp_efg_pct FLOAT, 
	opp_tov_pct FLOAT, 
	opp_oreb_pct FLOAT, 
	opp_ftr FLOAT, 
	off_rtg FLOAT, 
	def_rtg FLOAT, 
	net_rtg FLOAT, 
	pace FLOAT, 
	poss FLOAT, 
	is_estimated BOOLEAN NOT NULL, 
	data_source VARCHAR(16), 
	PRIMARY KEY (team_id, season, season_type), 
	FOREIGN KEY(team_id) REFERENCES teams (team_id)
);

CREATE INDEX ix_team_season_season ON team_season (season, season_type);

CREATE TABLE player_game_advanced (
	game_id VARCHAR(16) NOT NULL, 
	player_id INTEGER NOT NULL, 
	off_rtg FLOAT, 
	def_rtg FLOAT, 
	net_rtg FLOAT, 
	ast_pct FLOAT, 
	ast_tov FLOAT, 
	ast_ratio FLOAT, 
	oreb_pct FLOAT, 
	dreb_pct FLOAT, 
	reb_pct FLOAT, 
	tov_pct FLOAT, 
	efg_pct FLOAT, 
	ts_pct FLOAT, 
	usg_pct FLOAT, 
	pace FLOAT, 
	poss FLOAT, 
	pie FLOAT, 
	game_score FLOAT, 
	is_estimated BOOLEAN NOT NULL, 
	data_source VARCHAR(16), 
	PRIMARY KEY (game_id, player_id), 
	FOREIGN KEY(game_id) REFERENCES games (game_id), 
	FOREIGN KEY(player_id) REFERENCES players (player_id)
);

CREATE INDEX ix_pga_player ON player_game_advanced (player_id);

CREATE TABLE player_game_basic (
	game_id VARCHAR(16) NOT NULL, 
	player_id INTEGER NOT NULL, 
	team_id INTEGER NOT NULL, 
	started BOOLEAN, 
	minutes FLOAT, 
	fgm INTEGER, 
	fga INTEGER, 
	fg3m INTEGER, 
	fg3a INTEGER, 
	ftm INTEGER, 
	fta INTEGER, 
	oreb INTEGER, 
	dreb INTEGER, 
	reb INTEGER, 
	ast INTEGER, 
	stl INTEGER, 
	blk INTEGER, 
	tov INTEGER, 
	pf INTEGER, 
	pts INTEGER, 
	plus_minus FLOAT, 
	fantasy_pts FLOAT, 
	data_source VARCHAR(16), 
	PRIMARY KEY (game_id, player_id), 
	FOREIGN KEY(game_id) REFERENCES games (game_id), 
	FOREIGN KEY(player_id) REFERENCES players (player_id), 
	FOREIGN KEY(team_id) REFERENCES teams (team_id)
);

CREATE INDEX ix_pgb_player ON player_game_basic (player_id);
CREATE INDEX ix_pgb_team ON player_game_basic (team_id);

CREATE TABLE team_game (
	game_id VARCHAR(16) NOT NULL, 
	team_id INTEGER NOT NULL, 
	is_home BOOLEAN NOT NULL, 
	won BOOLEAN, 
	minutes FLOAT, 
	pts INTEGER, 
	opp_pts INTEGER, 
	fgm INTEGER, 
	fga INTEGER, 
	fg3m INTEGER, 
	fg3a INTEGER, 
	ftm INTEGER, 
	fta INTEGER, 
	oreb INTEGER, 
	dreb INTEGER, 
	reb INTEGER, 
	ast INTEGER, 
	stl INTEGER, 
	blk INTEGER, 
	tov INTEGER, 
	pf INTEGER, 
	plus_minus FLOAT, 
	fg_pct FLOAT, 
	fg3_pct FLOAT, 
	ft_pct FLOAT, 
	fg3a_rate FLOAT, 
	pps FLOAT, 
	ts_pct FLOAT, 
	efg_pct FLOAT, 
	tov_pct FLOAT, 
	oreb_pct FLOAT, 
	ftr FLOAT, 
	opp_efg_pct FLOAT, 
	opp_tov_pct FLOAT, 
	opp_oreb_pct FLOAT, 
	opp_ftr FLOAT, 
	off_rtg FLOAT, 
	def_rtg FLOAT, 
	net_rtg FLOAT, 
	pace FLOAT, 
	poss FLOAT, 
	data_source VARCHAR(16), 
	PRIMARY KEY (game_id, team_id), 
	FOREIGN KEY(game_id) REFERENCES games (game_id), 
	FOREIGN KEY(team_id) REFERENCES teams (team_id)
);

CREATE INDEX ix_team_game_team ON team_game (team_id);
