"""Every case in ``contracts/fixtures/format_cases.json``, replayed against
``nbastats.catalog.format_value`` — the Python side of the three-language parity
``contracts/tools/gen_parity_cases.py`` exists to pin (Swift's ``Formatting.swift``, the web's
``format.ts``, and this one).

The fixture is *generated by calling this exact function* (see that generator's own docstring),
so this test is not "does the implementation agree with a hand-written expectation" — it is
"does the implementation still produce what is committed", which is the guard against a future
edit to ``format_value`` silently drifting from the fixture the TypeScript and Swift test suites
also assert against. A rounding-mode or a formatting-rule change that does not also update this
fixture (via ``scripts/sync_contracts.sh``) fails here first.
"""
from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import pytest

from nbastats import catalog

FIXTURE_PATH = (
    Path(__file__).resolve().parents[2] / "contracts" / "fixtures" / "format_cases.json"
)


@pytest.fixture(scope="module")
def fixture() -> dict[str, Any]:
    assert FIXTURE_PATH.is_file(), f"{FIXTURE_PATH} is missing; run scripts/sync_contracts.sh"
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def test_em_dash_matches_the_catalogs_own_constant(fixture: dict[str, Any]) -> None:
    assert fixture["emDash"] == "—"
    assert catalog.format_value("integer", None) == fixture["emDash"]


def test_every_case_reproduces_byte_for_byte(fixture: dict[str, Any]) -> None:
    cases = fixture["cases"]
    assert cases, "the fixture carries no cases"
    for case in cases:
        actual = catalog.format_value(case["format"], case["value"])
        assert actual == case["expected"], (
            f"format_value({case['format']!r}, {case['value']!r}) = {actual!r}, "
            f"fixture says {case['expected']!r}"
        )


def test_null_always_renders_the_em_dash_never_zero(fixture: dict[str, Any]) -> None:
    """``contracts/CONTRACT.md`` §6: an era-unavailable stat is an em dash, never ``0``."""
    formats = {case["format"] for case in fixture["cases"]}
    for format_key in formats:
        assert catalog.format_value(format_key, None) == fixture["emDash"]
        assert catalog.format_value(format_key, None) != "0"


def test_plus_minus_is_signed_except_at_exactly_zero(fixture: dict[str, Any]) -> None:
    """The one case the fixture's own docstring calls out as an implementation change, not a
    description: ``format_value`` used to sign an exact zero (``"+0.0"``), which asserted a
    direction the number does not have. Both positive and negative zero must render unsigned."""
    zero_cases = [
        case
        for case in fixture["cases"]
        if case["format"] == "plusMinus1" and case["value"] is not None and case["value"] == 0.0
    ]
    assert len(zero_cases) == 2, "expected both +0.0 and -0.0 to be pinned"
    for case in zero_cases:
        assert case["expected"] == "0.0"
        assert catalog.format_value("plusMinus1", case["value"]) == "0.0"

    positive = catalog.format_value("plusMinus1", 7.8)
    negative = catalog.format_value("plusMinus1", -7.8)
    assert positive.startswith("+")
    assert negative.startswith("-")


def test_percent_formats_multiply_by_100_and_append_a_percent_sign() -> None:
    assert catalog.format_value("percent1", 0.615) == "61.5%"
    assert catalog.format_value("percent2", 0.6155) == "61.55%"


def test_negative_zero_is_not_the_same_bit_pattern_as_positive_zero() -> None:
    """A sanity check on the fixture's own two zero cases: ``-0.0`` really is negative zero in
    IEEE 754, so the case is exercising the sign-suppression rule and not merely repeating the
    ``0.0`` case under a different spelling."""
    assert math.copysign(1.0, -0.0) == -1.0
