-- Hardwood EuroLeague schema, generated by
-- nbastats.euroleague.models.render_schema_sql().
-- Do not edit by hand: run
-- `python3 -m nbastats.euroleague.models > nbastats/euroleague/schema.sql`.
-- Dialect: SQLite. These tables live on their own MetaData (ElBase) in their own file,
-- separate from nbastats/schema.sql -- see nbastats/euroleague/models.py for why.

CREATE TABLE el_club (
	club_code VARCHAR(8) NOT NULL, 
	tv_code VARCHAR(8), 
	name VARCHAR(96) NOT NULL, 
	short_name VARCHAR(48), 
	country_code VARCHAR(3), 
	PRIMARY KEY (club_code)
);

CREATE TABLE el_ingest_log (
	id INTEGER NOT NULL, 
	started_at DATETIME NOT NULL, 
	finished_at DATETIME, 
	job VARCHAR(32) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	games_written INTEGER, 
	rows_written INTEGER, 
	invariant_failed TEXT, 
	error TEXT, 
	source_sha256 VARCHAR(64), 
	detail_json TEXT, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_el_ingest_log_sha ON el_ingest_log (source_sha256);

CREATE TABLE el_intel_batch (
	batch_id INTEGER NOT NULL, 
	source_kind VARCHAR(20) NOT NULL, 
	label VARCHAR(96) NOT NULL, 
	file_sha256 VARCHAR(64), 
	imported_at DATETIME NOT NULL, 
	row_count INTEGER NOT NULL, 
	PRIMARY KEY (batch_id)
);

CREATE TABLE el_intel_news_feed (
	feed_id INTEGER NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	url TEXT NOT NULL, 
	enabled BOOLEAN NOT NULL, 
	robots_checked_on DATE, 
	disabled_reason VARCHAR(200), 
	etag VARCHAR(200), 
	last_modified VARCHAR(64), 
	last_fetch_at DATETIME, 
	last_status VARCHAR(64), 
	PRIMARY KEY (feed_id), 
	UNIQUE (url)
);

CREATE TABLE el_job_state (
	job_key VARCHAR(64) NOT NULL, 
	last_started_at DATETIME, 
	last_success_at DATETIME, 
	last_error TEXT, 
	cursor_json TEXT, 
	PRIMARY KEY (job_key)
);

CREATE TABLE el_model_setting (
	"key" VARCHAR(40) NOT NULL, 
	value FLOAT NOT NULL, 
	provenance VARCHAR(20) NOT NULL, 
	set_at DATETIME NOT NULL, 
	PRIMARY KEY ("key"), 
	CONSTRAINT ck_el_model_setting_key CHECK (key IN ('priorRegression', 'homeAdvantagePoints', 'teamSd', 'marginSd', 'replacementPer40', 'absorbShare', 'boostCap', 'rotationShare', 'formWeight', 'capPolicyConsistent', 'squadReconcile', 'overtimeScaling', 'roundWeight.1', 'roundWeight.2', 'roundWeight.3', 'roundWeight.4', 'roundWeight.5', 'roundWeight.6', 'roundWeight.7', 'roundWeight.8', 'roundWeight.9', 'roundWeight.10', 'roundWeight.11', 'roundWeight.12', 'roundWeight.13', 'roundWeight.14', 'roundWeight.15', 'roundWeight.16', 'roundWeight.17', 'roundWeight.18', 'roundWeight.19', 'roundWeight.20', 'roundWeight.21', 'roundWeight.22', 'roundWeight.23', 'roundWeight.24', 'roundWeight.25', 'roundWeight.26', 'roundWeight.27', 'roundWeight.28', 'roundWeight.29', 'roundWeight.30', 'roundWeight.31', 'roundWeight.32', 'roundWeight.33', 'roundWeight.34', 'roundWeight.35', 'roundWeight.36', 'roundWeight.37', 'roundWeight.38', 'roundWeight.39', 'roundWeight.40', 'statusChance.out', 'statusChance.doubtful', 'statusChance.questionable', 'statusChance.probable', 'statusChance.available', 'positionCoverageCeiling')), 
	CONSTRAINT ck_el_model_setting_prov CHECK (provenance IN ('workbook', 'workbookUnvalidated', 'default', 'fittedLedger', 'manual'))
);

CREATE TABLE el_person (
	person_code VARCHAR(16) NOT NULL, 
	code_system VARCHAR(10) NOT NULL, 
	name VARCHAR(96) NOT NULL, 
	display_name VARCHAR(96), 
	jersey_name VARCHAR(48), 
	birth_date DATE, 
	height_cm INTEGER, 
	weight_kg INTEGER, 
	country_code VARCHAR(3), 
	PRIMARY KEY (person_code), 
	CONSTRAINT ck_el_person_system CHECK (code_system IN ('official', 'workbook', 'demo'))
);

CREATE TABLE el_person_alias (
	wb_code VARCHAR(16) NOT NULL, 
	official_code VARCHAR(16) NOT NULL, 
	matched_by VARCHAR(12) NOT NULL, 
	matched_at DATETIME NOT NULL, 
	PRIMARY KEY (wb_code), 
	CONSTRAINT ck_el_person_alias_by CHECK (matched_by IN ('clubAndName', 'manual'))
);

CREATE TABLE el_raw_payload (
	payload_id INTEGER NOT NULL, 
	url TEXT NOT NULL, 
	endpoint_key VARCHAR(16), 
	fetched_at DATETIME NOT NULL, 
	http_status INTEGER, 
	sha256 VARCHAR(64), 
	bytes INTEGER, 
	path TEXT, 
	PRIMARY KEY (payload_id)
);

CREATE TABLE el_season (
	season_code VARCHAR(8) NOT NULL, 
	competition_code VARCHAR(4) NOT NULL, 
	label VARCHAR(8) NOT NULL, 
	start_year INTEGER NOT NULL, 
	is_current BOOLEAN NOT NULL, 
	PRIMARY KEY (season_code)
);

CREATE TABLE el_source_state (
	source_key VARCHAR(64) NOT NULL, 
	state VARCHAR(20) NOT NULL, 
	last_success_at DATETIME, 
	last_error TEXT, 
	consecutive_failures INTEGER NOT NULL, 
	paused_until DATETIME, 
	detail_json TEXT, 
	PRIMARY KEY (source_key)
);

CREATE TABLE el_store_identity (
	id INTEGER NOT NULL, 
	league VARCHAR(16) NOT NULL, 
	kind VARCHAR(12) NOT NULL, 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_el_store_identity_singleton CHECK (id = 1), 
	CONSTRAINT ck_el_store_identity_league CHECK (league = 'euroleague'), 
	CONSTRAINT ck_el_store_identity_kind CHECK (kind IN ('synthetic', 'workbook', 'live'))
);

CREATE TABLE el_sync_state (
	id INTEGER NOT NULL, 
	sync_version INTEGER NOT NULL, 
	data_through DATE, 
	mode VARCHAR(10) NOT NULL, 
	paused_until DATETIME, 
	last_success_at DATETIME, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_el_sync_state_singleton CHECK (id = 1), 
	CONSTRAINT ck_el_sync_state_mode CHECK (mode IN ('demo', 'workbook', 'live'))
);

CREATE TABLE el_club_alias (
	system VARCHAR(10) NOT NULL, 
	code VARCHAR(8) NOT NULL, 
	club_code VARCHAR(8) NOT NULL, 
	PRIMARY KEY (system, code), 
	CONSTRAINT ck_el_club_alias_system CHECK (system IN ('official', 'tv', 'workbook')), 
	FOREIGN KEY(club_code) REFERENCES el_club (club_code)
);

CREATE TABLE el_club_season (
	season_code VARCHAR(8) NOT NULL, 
	club_code VARCHAR(8) NOT NULL, 
	coach_name VARCHAR(96), 
	home_venue_name VARCHAR(128), 
	home_venue_tz VARCHAR(48), 
	PRIMARY KEY (season_code, club_code), 
	FOREIGN KEY(season_code) REFERENCES el_season (season_code), 
	FOREIGN KEY(club_code) REFERENCES el_club (club_code)
);

CREATE TABLE el_game (
	game_id VARCHAR(20) NOT NULL, 
	season_code VARCHAR(8) NOT NULL, 
	game_code INTEGER, 
	round_number INTEGER NOT NULL, 
	phase_code VARCHAR(2) NOT NULL, 
	game_date DATE NOT NULL, 
	tipoff_utc DATETIME, 
	venue_name VARCHAR(128), 
	venue_code VARCHAR(16), 
	is_neutral BOOLEAN, 
	home_advantage_override FLOAT, 
	home_club_code VARCHAR(8) NOT NULL, 
	away_club_code VARCHAR(8) NOT NULL, 
	status VARCHAR(10) NOT NULL, 
	home_pts INTEGER, 
	away_pts INTEGER, 
	home_partials_json TEXT, 
	away_partials_json TEXT, 
	ot_periods INTEGER, 
	attendance INTEGER, 
	stats_status VARCHAR(12) NOT NULL, 
	raw_sha256 VARCHAR(64), 
	data_source VARCHAR(24) NOT NULL, 
	ingested_at DATETIME NOT NULL, 
	PRIMARY KEY (game_id), 
	CONSTRAINT uq_el_game_season_code UNIQUE (season_code, game_code), 
	CONSTRAINT ck_el_game_phase CHECK (phase_code IN ('RS', 'PI', 'PO', 'FF')), 
	CONSTRAINT ck_el_game_status CHECK (status IN ('scheduled', 'final', 'postponed')), 
	CONSTRAINT ck_el_game_stats_status CHECK (stats_status IN ('none', 'ok', 'quarantined')), 
	CONSTRAINT ck_el_game_round CHECK (round_number >= 1), 
	CONSTRAINT ck_el_game_distinct_clubs CHECK (home_club_code <> away_club_code), 
	CONSTRAINT ck_el_game_final_has_score CHECK (status <> 'final' OR (home_pts IS NOT NULL AND away_pts IS NOT NULL)), 
	CONSTRAINT ck_el_game_stats_need_final CHECK (status = 'final' OR stats_status = 'none'), 
	CONSTRAINT ck_el_game_ot CHECK (ot_periods IS NULL OR ot_periods >= 0), 
	CONSTRAINT ck_el_game_attendance CHECK (attendance IS NULL OR attendance >= 0), 
	CONSTRAINT ck_el_game_data_source CHECK (data_source = 'euroleague-v2' OR data_source = 'synthetic-demo' OR data_source LIKE 'workbook:%'), 
	FOREIGN KEY(season_code) REFERENCES el_season (season_code), 
	FOREIGN KEY(home_club_code) REFERENCES el_club (club_code), 
	FOREIGN KEY(away_club_code) REFERENCES el_club (club_code)
);

CREATE INDEX ix_el_game_away ON el_game (away_club_code);
CREATE INDEX ix_el_game_home ON el_game (home_club_code);
CREATE INDEX ix_el_game_season_date ON el_game (season_code, game_date);
CREATE INDEX ix_el_game_season_round ON el_game (season_code, round_number);

CREATE TABLE el_intel_news_item (
	item_id INTEGER NOT NULL, 
	feed_id INTEGER, 
	guid VARCHAR(300), 
	title VARCHAR(300) NOT NULL, 
	link TEXT NOT NULL, 
	published_at DATETIME NOT NULL, 
	fetched_at DATETIME NOT NULL, 
	source_name VARCHAR(80) NOT NULL, 
	PRIMARY KEY (item_id), 
	CONSTRAINT uq_el_intel_news_item_guid UNIQUE (feed_id, guid), 
	FOREIGN KEY(feed_id) REFERENCES el_intel_news_feed (feed_id)
);

CREATE INDEX ix_el_intel_news_item_published ON el_intel_news_item (published_at);

CREATE TABLE el_player_rate (
	season_code VARCHAR(8) NOT NULL, 
	person_code VARCHAR(16) NOT NULL, 
	as_of_round INTEGER NOT NULL, 
	club_code VARCHAR(8) NOT NULL, 
	proj_minutes FLOAT, 
	pts40 FLOAT, 
	reb40 FLOAT, 
	ast40 FLOAT, 
	fg3m40 FLOAT, 
	stl40 FLOAT, 
	blk40 FLOAT, 
	tov40 FLOAT, 
	fga2_40 FLOAT, 
	fg2_pct FLOAT, 
	fga3_40 FLOAT, 
	fg3_pct FLOAT, 
	fta40 FLOAT, 
	ft_pct FLOAT, 
	basis VARCHAR(16) NOT NULL, 
	prior_minutes FLOAT NOT NULL, 
	PRIMARY KEY (season_code, person_code, as_of_round), 
	CONSTRAINT ck_el_player_rate_basis CHECK (basis IN ('workbookOfficial', 'workbookEstimate', 'positionPrior', 'officialUpdate', 'syntheticDemo')), 
	CONSTRAINT ck_el_player_rate_round CHECK (as_of_round >= 0), 
	CONSTRAINT ck_el_player_rate_prior CHECK (prior_minutes > 0), 
	CONSTRAINT ck_el_player_rate_fractions CHECK ((fg2_pct IS NULL OR (fg2_pct >= 0 AND fg2_pct <= 1)) AND (fg3_pct IS NULL OR (fg3_pct >= 0 AND fg3_pct <= 1)) AND (ft_pct IS NULL OR (ft_pct >= 0 AND ft_pct <= 1))), 
	FOREIGN KEY(season_code) REFERENCES el_season (season_code), 
	FOREIGN KEY(person_code) REFERENCES el_person (person_code), 
	FOREIGN KEY(club_code) REFERENCES el_club (club_code)
);

CREATE INDEX ix_el_player_rate_club ON el_player_rate (season_code, club_code, as_of_round);

CREATE TABLE el_registration (
	season_code VARCHAR(8) NOT NULL, 
	club_code VARCHAR(8) NOT NULL, 
	person_code VARCHAR(16) NOT NULL, 
	dorsal VARCHAR(4), 
	position_code SMALLINT, 
	position_name VARCHAR(24), 
	position5_workbook VARCHAR(2), 
	role_workbook VARCHAR(24), 
	age_workbook INTEGER, 
	active BOOLEAN, 
	start_date DATE, 
	end_date DATE, 
	source VARCHAR(16) NOT NULL, 
	PRIMARY KEY (season_code, club_code, person_code), 
	CONSTRAINT ck_el_registration_pos CHECK (position_code IS NULL OR position_code IN (1, 2, 3)), 
	CONSTRAINT ck_el_registration_pos5 CHECK (position5_workbook IS NULL OR position5_workbook IN ('PG', 'SG', 'SF', 'PF', 'C')), 
	FOREIGN KEY(season_code) REFERENCES el_season (season_code), 
	FOREIGN KEY(club_code) REFERENCES el_club (club_code), 
	FOREIGN KEY(person_code) REFERENCES el_person (person_code)
);

CREATE INDEX ix_el_registration_person ON el_registration (person_code);

CREATE TABLE el_team_rating (
	season_code VARCHAR(8) NOT NULL, 
	club_code VARCHAR(8) NOT NULL, 
	as_of_round INTEGER NOT NULL, 
	pf_prior FLOAT NOT NULL, 
	pa_prior FLOAT NOT NULL, 
	prior_is_estimate BOOLEAN NOT NULL, 
	attack_adj FLOAT NOT NULL, 
	defence_adj FLOAT NOT NULL, 
	source VARCHAR(16) NOT NULL, 
	update_weight FLOAT, 
	update_basis VARCHAR(14), 
	computed_at DATETIME NOT NULL, 
	PRIMARY KEY (season_code, club_code, as_of_round), 
	CONSTRAINT ck_el_team_rating_source CHECK (source IN ('workbookImport', 'roundUpdate', 'manual', 'syntheticDemo')), 
	CONSTRAINT ck_el_team_rating_basis CHECK (update_basis IS NULL OR update_basis IN ('locked', 'reconstructed')), 
	CONSTRAINT ck_el_team_rating_round CHECK (as_of_round >= 0), 
	FOREIGN KEY(season_code) REFERENCES el_season (season_code), 
	FOREIGN KEY(club_code) REFERENCES el_club (club_code)
);

CREATE TABLE el_intel_news_subject (
	item_id INTEGER NOT NULL, 
	club_code VARCHAR(8) NOT NULL, 
	person_code VARCHAR(16) NOT NULL, 
	PRIMARY KEY (item_id, club_code, person_code), 
	FOREIGN KEY(item_id) REFERENCES el_intel_news_item (item_id), 
	FOREIGN KEY(club_code) REFERENCES el_club (club_code)
);

CREATE TABLE el_intel_override (
	override_id INTEGER NOT NULL, 
	person_code VARCHAR(16) NOT NULL, 
	club_code VARCHAR(8), 
	game_id VARCHAR(20), 
	status VARCHAR(12) NOT NULL, 
	note VARCHAR(200), 
	source_url TEXT, 
	source_published_at DATETIME, 
	created_at DATETIME NOT NULL, 
	cleared_at DATETIME, 
	entered_by_user_id INTEGER, 
	PRIMARY KEY (override_id), 
	CONSTRAINT ck_el_intel_override_status CHECK (status IN ('out', 'doubtful', 'questionable', 'probable', 'available')), 
	FOREIGN KEY(person_code) REFERENCES el_person (person_code), 
	FOREIGN KEY(club_code) REFERENCES el_club (club_code), 
	FOREIGN KEY(game_id) REFERENCES el_game (game_id)
);

CREATE INDEX ix_el_intel_override_person ON el_intel_override (person_code);

CREATE TABLE el_intel_status (
	status_id INTEGER NOT NULL, 
	club_code VARCHAR(8) NOT NULL, 
	person_code VARCHAR(16), 
	player_name_raw VARCHAR(96) NOT NULL, 
	game_id VARCHAR(20), 
	game_date DATE, 
	status VARCHAR(12), 
	status_raw VARCHAR(48), 
	model_status VARCHAR(12), 
	reason_category VARCHAR(16), 
	reason_text VARCHAR(200), 
	expected_return_text VARCHAR(120), 
	expected_return_round_from INTEGER, 
	expected_return_round_to INTEGER, 
	expected_return_date DATE, 
	source_kind VARCHAR(20) NOT NULL, 
	source_label VARCHAR(160) NOT NULL, 
	source_url TEXT, 
	source_published_at DATETIME NOT NULL, 
	as_of DATETIME NOT NULL, 
	recorded_at DATETIME NOT NULL, 
	batch_id INTEGER, 
	entered_by_user_id INTEGER, 
	retracts_status_id INTEGER, 
	provenance_note VARCHAR(200), 
	PRIMARY KEY (status_id), 
	CONSTRAINT ck_el_intel_status_status CHECK (status IS NULL OR status IN ('out', 'doubtful', 'questionable', 'probable', 'available')), 
	CONSTRAINT ck_el_intel_status_model CHECK (model_status IS NULL OR model_status IN ('out', 'doubtful', 'questionable', 'probable', 'available')), 
	CONSTRAINT ck_el_intel_status_reason CHECK (reason_category IS NULL OR reason_category IN ('injury', 'illness', 'rest', 'coachDecision', 'personal', 'suspension', 'gLeague', 'notWithTeam', 'notRegistered', 'other')), 
	CONSTRAINT ck_el_intel_status_kind CHECK (source_kind IN ('leagueReport', 'clubStatement', 'pressArticle', 'boxScoreInference', 'workbookImport', 'manual')), 
	CONSTRAINT ck_el_intel_status_link CHECK (source_url IS NOT NULL OR source_kind = 'manual' OR source_label LIKE '%(link withheld: betting operator)'), 
	CONSTRAINT ck_el_intel_status_rounds CHECK (expected_return_round_from IS NULL OR expected_return_round_to IS NULL OR expected_return_round_to >= expected_return_round_from), 
	FOREIGN KEY(club_code) REFERENCES el_club (club_code), 
	FOREIGN KEY(person_code) REFERENCES el_person (person_code), 
	FOREIGN KEY(game_id) REFERENCES el_game (game_id), 
	FOREIGN KEY(batch_id) REFERENCES el_intel_batch (batch_id)
);

CREATE INDEX ix_el_intel_status_club ON el_intel_status (club_code, person_code);
CREATE INDEX ix_el_intel_status_published ON el_intel_status (source_published_at);

CREATE TABLE el_player_game (
	game_id VARCHAR(20) NOT NULL, 
	person_code VARCHAR(16) NOT NULL, 
	club_code VARCHAR(8) NOT NULL, 
	participation VARCHAR(8) NOT NULL, 
	is_starter BOOLEAN, 
	seconds_played INTEGER, 
	pts INTEGER, 
	fgm2 INTEGER, 
	fga2 INTEGER, 
	fgm3 INTEGER, 
	fga3 INTEGER, 
	ftm INTEGER, 
	fta INTEGER, 
	oreb INTEGER, 
	dreb INTEGER, 
	reb INTEGER, 
	ast INTEGER, 
	stl INTEGER, 
	tov INTEGER, 
	blk INTEGER, 
	blk_against INTEGER, 
	pf INTEGER, 
	fouls_drawn INTEGER, 
	plus_minus INTEGER, 
	pir_official INTEGER, 
	position_code_at_game SMALLINT, 
	dorsal VARCHAR(4), 
	PRIMARY KEY (game_id, person_code), 
	CONSTRAINT ck_el_player_game_part CHECK (participation IN ('played', 'dnp')), 
	CONSTRAINT ck_el_player_game_dnp_null CHECK (participation = 'played' OR (seconds_played IS NULL AND pts IS NULL AND fgm2 IS NULL AND fga2 IS NULL AND fgm3 IS NULL AND fga3 IS NULL AND ftm IS NULL AND fta IS NULL AND oreb IS NULL AND dreb IS NULL AND reb IS NULL AND ast IS NULL AND stl IS NULL AND tov IS NULL AND blk IS NULL AND blk_against IS NULL AND pf IS NULL AND fouls_drawn IS NULL AND plus_minus IS NULL AND pir_official IS NULL)), 
	CONSTRAINT ck_el_player_game_seconds_played_nonneg CHECK (seconds_played IS NULL OR seconds_played >= 0), 
	CONSTRAINT ck_el_player_game_pts_nonneg CHECK (pts IS NULL OR pts >= 0), 
	CONSTRAINT ck_el_player_game_fgm2_nonneg CHECK (fgm2 IS NULL OR fgm2 >= 0), 
	CONSTRAINT ck_el_player_game_fga2_nonneg CHECK (fga2 IS NULL OR fga2 >= 0), 
	CONSTRAINT ck_el_player_game_fgm3_nonneg CHECK (fgm3 IS NULL OR fgm3 >= 0), 
	CONSTRAINT ck_el_player_game_fga3_nonneg CHECK (fga3 IS NULL OR fga3 >= 0), 
	CONSTRAINT ck_el_player_game_ftm_nonneg CHECK (ftm IS NULL OR ftm >= 0), 
	CONSTRAINT ck_el_player_game_fta_nonneg CHECK (fta IS NULL OR fta >= 0), 
	CONSTRAINT ck_el_player_game_oreb_nonneg CHECK (oreb IS NULL OR oreb >= 0), 
	CONSTRAINT ck_el_player_game_dreb_nonneg CHECK (dreb IS NULL OR dreb >= 0), 
	CONSTRAINT ck_el_player_game_reb_nonneg CHECK (reb IS NULL OR reb >= 0), 
	CONSTRAINT ck_el_player_game_ast_nonneg CHECK (ast IS NULL OR ast >= 0), 
	CONSTRAINT ck_el_player_game_stl_nonneg CHECK (stl IS NULL OR stl >= 0), 
	CONSTRAINT ck_el_player_game_tov_nonneg CHECK (tov IS NULL OR tov >= 0), 
	CONSTRAINT ck_el_player_game_blk_nonneg CHECK (blk IS NULL OR blk >= 0), 
	CONSTRAINT ck_el_player_game_blk_against_nonneg CHECK (blk_against IS NULL OR blk_against >= 0), 
	CONSTRAINT ck_el_player_game_pf_nonneg CHECK (pf IS NULL OR pf >= 0), 
	CONSTRAINT ck_el_player_game_fouls_drawn_nonneg CHECK (fouls_drawn IS NULL OR fouls_drawn >= 0), 
	CONSTRAINT ck_el_player_game_fgm2_le_fga2 CHECK (fgm2 IS NULL OR fga2 IS NULL OR fgm2 <= fga2), 
	CONSTRAINT ck_el_player_game_fgm3_le_fga3 CHECK (fgm3 IS NULL OR fga3 IS NULL OR fgm3 <= fga3), 
	CONSTRAINT ck_el_player_game_ftm_le_fta CHECK (ftm IS NULL OR fta IS NULL OR ftm <= fta), 
	FOREIGN KEY(game_id) REFERENCES el_game (game_id), 
	FOREIGN KEY(person_code) REFERENCES el_person (person_code), 
	FOREIGN KEY(club_code) REFERENCES el_club (club_code)
);

CREATE INDEX ix_el_player_game_club ON el_player_game (club_code);
CREATE INDEX ix_el_player_game_person ON el_player_game (person_code);

CREATE TABLE el_projection_ledger (
	ledger_id INTEGER NOT NULL, 
	game_id VARCHAR(20) NOT NULL, 
	kind VARCHAR(14) NOT NULL, 
	model_version VARCHAR(24) NOT NULL, 
	computed_at DATETIME, 
	inputs_cutoff DATETIME, 
	home_pts FLOAT NOT NULL, 
	away_pts FLOAT NOT NULL, 
	home_full_strength FLOAT, 
	away_full_strength FLOAT, 
	home_attack_index_after_availability FLOAT, 
	away_attack_index_after_availability FLOAT, 
	home_defence_index FLOAT, 
	away_defence_index FLOAT, 
	home_advantage_points FLOAT, 
	cap_policy VARCHAR(12) NOT NULL, 
	settings_sha256 VARCHAR(64), 
	inputs_sha256 VARCHAR(64), 
	availability_as_of DATETIME, 
	PRIMARY KEY (ledger_id), 
	CONSTRAINT ck_el_ledger_kind CHECK (kind IN ('latest', 'locked', 'reconstructed', 'imported')), 
	CONSTRAINT ck_el_ledger_cap_policy CHECK (cap_policy IN ('consistent', 'workbook')), 
	CONSTRAINT ck_el_ledger_complete CHECK (kind = 'imported' OR (computed_at IS NOT NULL AND inputs_cutoff IS NOT NULL AND home_full_strength IS NOT NULL AND away_full_strength IS NOT NULL AND home_attack_index_after_availability IS NOT NULL AND away_attack_index_after_availability IS NOT NULL AND home_defence_index IS NOT NULL AND away_defence_index IS NOT NULL AND home_advantage_points IS NOT NULL)), 
	FOREIGN KEY(game_id) REFERENCES el_game (game_id)
);

CREATE INDEX ix_el_ledger_game ON el_projection_ledger (game_id, kind);

CREATE TABLE el_team_game (
	game_id VARCHAR(20) NOT NULL, 
	club_code VARCHAR(8) NOT NULL, 
	is_home BOOLEAN NOT NULL, 
	opp_club_code VARCHAR(8) NOT NULL, 
	won BOOLEAN, 
	seconds_played INTEGER, 
	pts INTEGER NOT NULL, 
	opp_pts INTEGER NOT NULL, 
	fgm2 INTEGER, 
	fga2 INTEGER, 
	fgm3 INTEGER, 
	fga3 INTEGER, 
	ftm INTEGER, 
	fta INTEGER, 
	oreb INTEGER, 
	dreb INTEGER, 
	reb INTEGER, 
	ast INTEGER, 
	stl INTEGER, 
	tov INTEGER, 
	blk INTEGER, 
	blk_against INTEGER, 
	pf INTEGER, 
	fouls_drawn INTEGER, 
	plus_minus INTEGER, 
	pir_official INTEGER, 
	PRIMARY KEY (game_id, club_code), 
	CONSTRAINT ck_el_team_game_scores CHECK (pts >= 0 AND opp_pts >= 0), 
	CONSTRAINT ck_el_team_game_seconds_played_nonneg CHECK (seconds_played IS NULL OR seconds_played >= 0), 
	CONSTRAINT ck_el_team_game_pts_nonneg CHECK (pts IS NULL OR pts >= 0), 
	CONSTRAINT ck_el_team_game_fgm2_nonneg CHECK (fgm2 IS NULL OR fgm2 >= 0), 
	CONSTRAINT ck_el_team_game_fga2_nonneg CHECK (fga2 IS NULL OR fga2 >= 0), 
	CONSTRAINT ck_el_team_game_fgm3_nonneg CHECK (fgm3 IS NULL OR fgm3 >= 0), 
	CONSTRAINT ck_el_team_game_fga3_nonneg CHECK (fga3 IS NULL OR fga3 >= 0), 
	CONSTRAINT ck_el_team_game_ftm_nonneg CHECK (ftm IS NULL OR ftm >= 0), 
	CONSTRAINT ck_el_team_game_fta_nonneg CHECK (fta IS NULL OR fta >= 0), 
	CONSTRAINT ck_el_team_game_oreb_nonneg CHECK (oreb IS NULL OR oreb >= 0), 
	CONSTRAINT ck_el_team_game_dreb_nonneg CHECK (dreb IS NULL OR dreb >= 0), 
	CONSTRAINT ck_el_team_game_reb_nonneg CHECK (reb IS NULL OR reb >= 0), 
	CONSTRAINT ck_el_team_game_ast_nonneg CHECK (ast IS NULL OR ast >= 0), 
	CONSTRAINT ck_el_team_game_stl_nonneg CHECK (stl IS NULL OR stl >= 0), 
	CONSTRAINT ck_el_team_game_tov_nonneg CHECK (tov IS NULL OR tov >= 0), 
	CONSTRAINT ck_el_team_game_blk_nonneg CHECK (blk IS NULL OR blk >= 0), 
	CONSTRAINT ck_el_team_game_blk_against_nonneg CHECK (blk_against IS NULL OR blk_against >= 0), 
	CONSTRAINT ck_el_team_game_pf_nonneg CHECK (pf IS NULL OR pf >= 0), 
	CONSTRAINT ck_el_team_game_fouls_drawn_nonneg CHECK (fouls_drawn IS NULL OR fouls_drawn >= 0), 
	CONSTRAINT ck_el_team_game_fgm2_le_fga2 CHECK (fgm2 IS NULL OR fga2 IS NULL OR fgm2 <= fga2), 
	CONSTRAINT ck_el_team_game_fgm3_le_fga3 CHECK (fgm3 IS NULL OR fga3 IS NULL OR fgm3 <= fga3), 
	CONSTRAINT ck_el_team_game_ftm_le_fta CHECK (ftm IS NULL OR fta IS NULL OR ftm <= fta), 
	FOREIGN KEY(game_id) REFERENCES el_game (game_id), 
	FOREIGN KEY(club_code) REFERENCES el_club (club_code), 
	FOREIGN KEY(opp_club_code) REFERENCES el_club (club_code)
);

CREATE INDEX ix_el_team_game_club ON el_team_game (club_code);
