"""The dashboard-layout migrator — a Python port of ``ios/NBAStats/Core/LayoutMigrator.swift``.

Why this is a port, not a reimplementation from the widget catalog alone
--------------------------------------------------------------------------
Hardwood Web stores exactly the same ``DashboardLayout`` JSON document iOS does
(``accounts/models.py::UserDashboard.document_json``, "the entire ``DashboardLayout`` JSON,
verbatim — the truth"), and a document written by one client has to open cleanly in the other.
That is only true if both clients apply the *same* migration rules in the *same* order, right
down to the note strings a person reads when something was silently repaired. So there are two
implementations of the migration rules on purpose — Swift for the app, this module for the
server — never three: the web does **not** re-implement this in TypeScript. It sends a raw
layout document to the API and receives back whatever this module decided, exactly the same
way an iOS device would have decided it locally.

``contracts/fixtures/layout_migration_cases.json`` (generated by
``contracts/tools/gen_parity_cases.py`` from a *reference* port kept in that generator, not from
this module) pins the two implementations together; ``backend/tests/test_layout_parity.py``
replays every case in that fixture against the real functions below and fails the moment this
module's behaviour drifts from the fixture the Swift test suite also asserts. The note strings
are product copy shared with iOS and are copied here **verbatim**, curly quotes included
(``LayoutMigrator.swift``'s private ``listPhrase`` also uses U+201C/U+201D, not ASCII quotes).

The two tiers, and why they are separate functions
-----------------------------------------------------
* **Tier 1 — schema level** (:func:`migrate_document`). Needs no widget catalog: it repairs the
  document shape itself (a missing id, a duplicate id, an unknown widget kind, an unrecognised
  size) and enforces the one-way ``schemaVersion`` ratchet. A layout from a *newer* build always
  raises :class:`LayoutTooNew` rather than being guessed at and silently corrupted — "a
  best-effort parse that then saves would destroy fields this build does not know about"
  (``WEB_DESIGN.md`` §2.10).
* **Tier 2 — catalog level** (:func:`normalize`). Runs each surviving widget's config against
  ``nbastats.catalog`` — the *same* ``widget_kinds()``, ``widget()`` and
  ``widget_config_defaults()`` the API resolver and the web app both read — so there is one
  definition of "this config is valid" for the API, the web and CI, not a second copy of the
  widget field lists hand-maintained in this file.

``migrate_and_normalize`` runs both, in order, with notes concatenated tier 1 first: a widget
dropped in tier 1 for having an unknown kind never reaches tier 2's per-field checks, and a note
about a size falling back to "medium" (tier 1) always reads before a note about that same widget
losing an unsupported size later (tier 2 cannot happen to a tier-1-dropped widget, but where both
fire on a *surviving* widget the reading order matches the order the rules actually ran in).

Every public function here is deliberately free of I/O and of the request/session layer:
``accounts/store.py`` is the only caller, and it is the one that knows about a database row.
"""
from __future__ import annotations

import json
import uuid
from dataclasses import dataclass
from typing import Any

from .. import catalog

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "KNOWN_SIZES",
    "KNOWN_ACCENTS",
    "KNOWN_PRESENTATIONS",
    "DEFAULT_SIZE",
    "DEFAULT_ACCENT",
    "DEFAULT_PRESENTATION",
    "DEFAULT_ICON",
    "DEFAULT_NAME",
    "FALLBACK_WIDGET_NAMES",
    "display_name",
    "LayoutTooNew",
    "NotALayout",
    "UnreadableLayout",
    "MigrationResult",
    "humanize_list",
    "fresh_id",
    "migrate_document",
    "normalize",
    "migrate_and_normalize",
    "migrate_collection",
    "canonical_json",
    "fork_preset",
    "seed_layout_for_new_user",
]

#: The one-way ratchet. A document naming a higher value was written by a newer build; this
#: build refuses to touch it rather than guess at fields it does not know (see the module
#: docstring). Bumping this number is a decision for whoever next changes the layout shape, not
#: something this module ever does on its own.
CURRENT_SCHEMA_VERSION = 1

KNOWN_SIZES: tuple[str, ...] = ("small", "medium", "large")
DEFAULT_SIZE = "medium"

#: ``ios/NBAStats/Core/DashboardLayout.swift::AccentName`` — order does not matter here (only
#: membership does), but it is kept in the enum's declared order for a reader comparing the two.
KNOWN_ACCENTS: tuple[str, ...] = (
    "orange", "indigo", "teal", "red", "amber", "green", "blue", "purple", "graphite",
)
DEFAULT_ACCENT = "orange"

#: ``LayoutPresentation``. An unrecognised value falls back silently, exactly like an
#: unrecognised accent — neither is product-facing enough to explain in a note.
KNOWN_PRESENTATIONS: tuple[str, ...] = ("tiles", "broadsheet")
DEFAULT_PRESENTATION = "tiles"

DEFAULT_ICON = "square.grid.2x2"
DEFAULT_NAME = "Dashboard"

#: ``ios/NBAStats/Core/DashboardLayout.swift::WidgetKind.fallbackName`` — the compile-time
#: display name Swift falls back to when it has no catalog. Tier 1 is *catalog-free* in both
#: implementations (``LayoutMigrator.swift``'s schema tier never touches a ``Catalog``), so the
#: table is transcribed here rather than read from ``contracts/widgets.json``: a note a reader
#: sees must not depend on whether a catalog happened to load. The values match
#: ``widgets.json``'s ``name`` for all sixteen kinds today, and
#: ``test_layout_parity.py::test_fallback_names_match_the_catalog`` fails if that ever drifts.
FALLBACK_WIDGET_NAMES: dict[str, str] = {
    "stat_tile": "Stat Tile",
    "player_snapshot": "Player Snapshot",
    "leaderboard": "Leaderboard",
    "game_log": "Game Log",
    "trend_chart": "Trend",
    "four_factors": "Four Factors",
    "shot_profile": "Shot Profile",
    "comparison": "Comparison",
    "scoreboard": "Scoreboard",
    "daily_movers": "Daily Movers",
    "team_efficiency": "Team Efficiency",
    "next_game_projection": "Next Game",
    "projection_board": "Tonight's Projections",
    "fantasy_draft_board": "Draft Board",
    "fantasy_trade": "Trade Analyzer",
    "career_arc": "Career Arc",
}


def display_name(kind: str) -> str:
    """The reader-facing name of a widget kind, for a note about an *untitled* widget.

    ``LayoutMigrator.swift`` prints ``WidgetKind.fallbackName`` in exactly these two places
    (the tier-1 unknown-size note and the tier-2 removed-widget note); printing the raw
    ``snake_case`` kind instead — which this module used to do — meant one API response could
    name the same widget ``“stat_tile”`` in one note and ``“Stat Tile”`` in the next, and meant
    the note a person read depended on which client had repaired the file. An unrecognised kind
    (only reachable through :func:`normalize`'s test seam, since tier 1 has already dropped
    anything the catalog does not know) falls back to the raw kind.
    """
    return FALLBACK_WIDGET_NAMES.get(kind, kind)


#: Timestamps the document carries that this build does not interpret but must not destroy:
#: ``LayoutMigrator.swift`` passes both straight through (``Formatting.parseTimestamp``) and
#: ``DashboardLayout.encode`` writes them back out, ``LayoutSwitcher.swift`` renders the
#: freshness line from ``updatedAt``, and ``DashboardStore.swift`` restores ``createdAt``. A
#: round trip iOS -> web -> export -> iOS has to return them unchanged.
_PASSTHROUGH_TIMESTAMP_KEYS = ("createdAt", "updatedAt")


def _carried_timestamps(document: dict[str, Any]) -> dict[str, str]:
    """``createdAt``/``updatedAt`` from ``document``, when each is a non-empty string. Anything
    else (a number, a null, an empty string) is dropped rather than guessed at — Swift's
    ``parseTimestamp`` returns ``nil`` for those too, and encoding skips a ``nil``."""
    carried: dict[str, str] = {}
    for key in _PASSTHROUGH_TIMESTAMP_KEYS:
        value = document.get(key)
        if isinstance(value, str) and value:
            carried[key] = value
    return carried

#: The preset a brand-new account's very first dashboard is forked from (§2.10).
_SEED_PRESET_KEY = "daily_recap"


class LayoutTooNew(Exception):
    """Raised by :func:`migrate_document` when ``schemaVersion`` exceeds what this build reads.

    The ratchet is one-way and this is the one tier-1 failure that never migrates: a best-effort
    parse that then saved the document would silently drop every field a newer build added.
    """

    def __init__(self, found: int, supported: int) -> None:
        self.found = found
        self.supported = supported
        super().__init__(
            f"This dashboard was made with a newer version of Hardwood (format {found}; "
            f"this build reads {supported}). Update the app to edit it."
        )


class NotALayout(Exception):
    """Raised when a decoded JSON value has none of ``name``, ``widgets`` or ``id`` — the
    weakest possible signal that this was ever a dashboard document at all."""

    def __init__(self) -> None:
        super().__init__("This file does not contain a dashboard.")


class UnreadableLayout(Exception):
    """Raised when the raw input is not even valid JSON."""

    def __init__(self) -> None:
        super().__init__("This dashboard file could not be read.")


@dataclass(frozen=True, slots=True)
class MigrationResult:
    """A migrated (and/or normalized) layout, plus every note a person should read about it."""

    layout: dict[str, Any]
    notes: list[str]


def _timestamp_now() -> str:
    """``Formatting.timestampString(Date())``'s wire shape — ``ISO8601DateFormatter`` with
    ``.withInternetDateTime``, i.e. whole seconds and a literal ``Z``."""
    from ..db import utcnow

    return utcnow().replace(microsecond=0).isoformat() + "Z"


def fresh_id() -> str:
    """A fresh widget or layout id. Format-compatible with, but never compared against, an
    iOS-minted ``UUID().uuidString`` — both are opaque strings from the reader's point of view.
    Public because ``accounts/store.py`` needs the same minting rule to repair a client-supplied
    layout id that collides with one this user already holds (POST creates, it never overwrites).
    """
    return uuid.uuid4().hex


def humanize_list(items: list[str]) -> str:
    """``["a"]`` -> ``"a"``, ``["a", "b", "c"]`` -> ``"a", "b" and "c"`` — curly-quoted per item,
    no Oxford comma. A direct port of ``LayoutMigrator.swift``'s private ``listPhrase``,
    including its quote character (U+201C/U+201D, not ASCII ``"``), because these strings are
    product copy shared verbatim with iOS."""
    quoted = [f"“{item}”" for item in items]
    if not quoted:
        return ""
    if len(quoted) == 1:
        return quoted[0]
    return ", ".join(quoted[:-1]) + " and " + quoted[-1]


def _parse(raw: Any) -> Any:
    """Decode ``raw`` if it is text; pass a value that already decoded straight through."""
    if isinstance(raw, (str, bytes, bytearray)):
        try:
            return json.loads(raw)
        except (ValueError, TypeError) as exc:
            raise UnreadableLayout() from exc
    return raw


def _schema_version_of(document: dict[str, Any]) -> int:
    """The document's ``schemaVersion``, for the one-way ratchet in :func:`migrate_document`.

    Absent or ``null`` means "written by a build that did not stamp one", which is this build's
    own version — the same ``document.schemaVersion ?? currentSchemaVersion`` Swift applies.
    Anything else must be a JSON **number**: ``json.loads`` hands back ``2.0`` (a float) for the
    perfectly legal JSON ``2.0``, and a ``"2"`` string for a re-serialised document, and this
    module used to silently treat both as "no version at all" — defeating the ratchet and then
    stamping the future document down to version 1, which is precisely the silent corruption the
    module docstring says cannot happen. Swift's ``RawLayout.schemaVersion`` is an ``Int?``, so
    ``JSONDecoder`` reads ``2.0`` as ``2`` and *throws* on ``"2"`` — and a throw out of
    ``JSONDecoder`` is exactly what ``migrateResult(_:)`` reports as ``.unreadable``. This
    matches both: an integral number is the version, anything else is
    :class:`UnreadableLayout`.
    """
    raw_version = document.get("schemaVersion")
    if raw_version is None:
        return CURRENT_SCHEMA_VERSION
    if isinstance(raw_version, bool) or not isinstance(raw_version, (int, float)):
        raise UnreadableLayout()
    if isinstance(raw_version, float) and not raw_version.is_integer():
        raise UnreadableLayout()
    return int(raw_version)


def migrate_document(raw: Any) -> MigrationResult:
    """Tier 1: schema-level migration, catalog-free.

    ``raw`` may be a JSON string/bytes (parsed here, an ``UnreadableLayout`` on bad JSON) or an
    already-decoded value. Anything that decodes to something other than a JSON object, or an
    object with none of ``name``, ``widgets`` or ``id``, is :class:`NotALayout`.
    """
    document = _parse(raw)
    if not isinstance(document, dict):
        raise NotALayout()

    # Order matters, and it is Swift's: `migrateResult(_:)` decodes the whole `RawLayout` first
    # (so a field of the wrong *type* is `.unreadable`), then applies the version ratchet, and
    # only then asks whether anything layout-shaped is present at all. Testing "is this a
    # layout?" first would answer `NotALayout` where iOS answers `LayoutTooNew` for the very
    # same bytes.
    found_version = _schema_version_of(document)
    if found_version > CURRENT_SCHEMA_VERSION:
        raise LayoutTooNew(found_version, CURRENT_SCHEMA_VERSION)
    if document.get("name") is None and document.get("widgets") is None and document.get("id") is None:
        raise NotALayout()

    notes: list[str] = []
    widgets: list[dict[str, Any]] = []
    used_ids: set[str] = set()
    known_kinds = set(catalog.widget_kinds())

    for raw_widget in document.get("widgets") or []:
        if not isinstance(raw_widget, dict):
            # A widget entry that is not even an object: "failed to decode entirely" (§2.10's
            # table folds this into the same note as a missing `kind`).
            notes.append("Removed a widget that had no type.")
            continue

        kind_raw = raw_widget.get("kind")
        if kind_raw is None:
            notes.append("Removed a widget that had no type.")
            continue
        if kind_raw not in known_kinds:
            notes.append(
                f"Removed a “{kind_raw}” widget: this version of Hardwood does not "
                "have that widget."
            )
            continue

        size_raw = raw_widget.get("size")
        if size_raw is not None:
            if size_raw in KNOWN_SIZES:
                size = size_raw
            else:
                size = DEFAULT_SIZE
                title_or_fallback = raw_widget.get("title") or display_name(kind_raw)
                notes.append(
                    f"“{title_or_fallback}”: the size “{size_raw}” is "
                    "unknown, so it is medium now."
                )
        else:
            size = DEFAULT_SIZE

        widget_id = raw_widget.get("id") or fresh_id()
        if not isinstance(widget_id, str) or not widget_id:
            widget_id = fresh_id()
        if widget_id in used_ids:
            widget_id = fresh_id()
            notes.append("Two widgets shared an id; one of them was given a new one.")
        used_ids.add(widget_id)

        widgets.append(
            {
                "id": widget_id,
                "kind": kind_raw,
                "title": raw_widget.get("title"),
                "size": size,
                "config": raw_widget.get("config") or {},
            }
        )

    accent_raw = document.get("accent")
    accent = accent_raw if accent_raw in KNOWN_ACCENTS else DEFAULT_ACCENT
    presentation_raw = document.get("presentation")
    presentation = (
        presentation_raw if presentation_raw in KNOWN_PRESENTATIONS else DEFAULT_PRESENTATION
    )

    layout_id = document.get("id") or fresh_id()
    if not isinstance(layout_id, str) or not layout_id:
        layout_id = fresh_id()

    layout: dict[str, Any] = {
        "id": layout_id,
        "name": document.get("name") or DEFAULT_NAME,
        "icon": document.get("icon") or DEFAULT_ICON,
        "accent": accent,
        "presentation": presentation,
        "schemaVersion": CURRENT_SCHEMA_VERSION,
        "isPreset": bool(document.get("isPreset") or False),
        "presetKey": document.get("presetKey"),
        "tagline": document.get("tagline"),
        **_carried_timestamps(document),
        "widgets": widgets,
    }
    if found_version < CURRENT_SCHEMA_VERSION:
        notes.append(f"Updated this dashboard from format {found_version} to {CURRENT_SCHEMA_VERSION}.")
    return MigrationResult(layout=layout, notes=notes)


def normalize(layout: dict[str, Any], *, available_kinds: Any = None) -> MigrationResult:
    """Tier 2: validate every widget's config against ``nbastats.catalog``.

    ``available_kinds`` is a private test seam (default: ``catalog.widget_kinds()``) that lets
    ``test_layout_parity.py`` exercise the fixture's "a kind the schema still allows but a live
    catalog has stopped serving" case without a second production code path; production callers
    never pass it.
    """
    known_kinds = set(available_kinds) if available_kinds is not None else set(catalog.widget_kinds())
    notes: list[str] = []
    kept: list[dict[str, Any]] = []

    for widget in layout.get("widgets") or []:
        kind = widget["kind"]
        title = widget.get("title")
        if kind not in known_kinds:
            notes.append(
                f"Removed “{title or display_name(kind)}”: this version of Hardwood no "
                "longer has that widget."
            )
            continue

        spec = catalog.widget(kind)
        field_keys = {field["key"] for field in spec["config"]}
        defaults = catalog.widget_config_defaults(kind)
        raw_config = widget.get("config") or {}

        normalized: dict[str, Any] = {}
        for key in field_keys:
            if key in raw_config and raw_config[key] is not None:
                normalized[key] = raw_config[key]
            elif defaults.get(key) is not None:
                normalized[key] = defaults[key]
            elif key in raw_config:
                normalized[key] = None  # explicit null, no default: kept, not filled.

        dropped = sorted(key for key in raw_config if key not in normalized)
        if dropped:
            notes.append(
                f"“{title or spec['name']}”: removed {humanize_list(dropped)}, which "
                "this widget no longer uses."
            )
        filled = sorted(key for key in normalized if key not in raw_config)
        if filled:
            notes.append(
                f"“{title or spec['name']}”: filled in {humanize_list(filled)} from "
                "the defaults."
            )

        updated = dict(widget, config=normalized)
        sizes = spec["sizes"]
        if widget["size"] not in sizes:
            default_size = spec["defaultSize"]
            notes.append(
                f"“{title or spec['name']}”: resized to {default_size.capitalize()}, "
                "the only size it supports now."
            )
            updated["size"] = default_size
        kept.append(updated)

    return MigrationResult(layout=dict(layout, widgets=kept), notes=notes)


def migrate_and_normalize(raw: Any) -> MigrationResult:
    """Both tiers, in order, notes concatenated tier 1 then tier 2 (see the module docstring)."""
    tier1 = migrate_document(raw)
    tier2 = normalize(tier1.layout)
    return MigrationResult(layout=tier2.layout, notes=[*tier1.notes, *tier2.notes])


def migrate_collection(raw: Any) -> tuple[list[MigrationResult], list[str]]:
    """Accept the iOS envelope ``{schemaVersion, updatedAt, layouts: [...]}``, a bare array, or a
    single bare layout object — the three shapes ``LayoutMigrator.migrateCollection`` takes.

    Each layout migrates independently: one corrupt entry is recorded as a failure note and the
    rest of the collection is unaffected, which is the whole point of an import path that a
    person might feed a partially-hand-edited export.
    """
    document = _parse(raw)
    if isinstance(document, dict) and "layouts" in document:
        candidates: list[Any] = list(document.get("layouts") or [])
    elif isinstance(document, list):
        candidates = list(document)
    else:
        candidates = [document]

    results: list[MigrationResult] = []
    failures: list[str] = []
    for candidate in candidates:
        try:
            results.append(migrate_and_normalize(candidate))
        except (LayoutTooNew, NotALayout, UnreadableLayout) as exc:
            failures.append(str(exc))
    return results, failures


def canonical_json(layout: dict[str, Any]) -> str:
    """Byte-compatible with Swift's ``JSONEncoder.outputFormatting = [.sortedKeys]`` — sorted
    keys, no extra whitespace, real Unicode rather than ``\\uXXXX`` escapes."""
    return json.dumps(layout, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def fork_preset(preset: dict[str, Any]) -> tuple[dict[str, Any], dict[str, str]]:
    """``makeEditableCopy()``: a fresh layout id, fresh widget ids, ``isPreset=False``, the
    ``presetKey`` retained (so "reset to the shipped version" stays possible).

    Returns ``(layout, old_widget_id -> new_widget_id)`` — the id map matters because a caller
    that captured a widget id from the *unforked* preset (the preset gallery preview, say) still
    needs to find that same widget in the copy it just created.
    """
    id_map: dict[str, str] = {}
    widgets: list[dict[str, Any]] = []
    for widget in preset.get("widgets") or []:
        old_id = widget.get("id")
        new_id = fresh_id()
        if isinstance(old_id, str):
            id_map[old_id] = new_id
        widgets.append({**widget, "id": new_id})

    # `makeEditableCopy()` stamps a *fresh* `now` into both timestamps (DashboardLayout.swift:
    # 270-286): a fork is a new dashboard, not a copy of an old one's history.
    now = _timestamp_now()
    layout = {
        "id": fresh_id(),
        "name": preset.get("name") or DEFAULT_NAME,
        "icon": preset.get("icon") or DEFAULT_ICON,
        "accent": preset.get("accent") or DEFAULT_ACCENT,
        "presentation": preset.get("presentation") or DEFAULT_PRESENTATION,
        "schemaVersion": CURRENT_SCHEMA_VERSION,
        "isPreset": False,
        "presetKey": preset.get("presetKey"),
        "tagline": preset.get("tagline"),
        "createdAt": now,
        "updatedAt": now,
        "widgets": widgets,
    }
    return layout, id_map


def seed_layout_for_new_user() -> dict[str, Any]:
    """A brand-new account's first dashboard: a fork of the ``daily_recap`` preset, kept as a
    preset (``isPreset=True``, ``presetKey="daily_recap"``) rather than an editable copy — the
    one place a fork is not the "edit this" action, because nobody has asked to edit it yet."""
    layout, _id_map = fork_preset(catalog.preset(_SEED_PRESET_KEY))
    layout["isPreset"] = True
    layout["presetKey"] = _SEED_PRESET_KEY
    return layout
