-- Hardwood accounts schema, generated by nbastats.accounts.models.render_schema_sql().
-- Do not edit by hand: run
-- `python3 -m nbastats.accounts.models > nbastats/accounts/schema.sql`.
-- Dialect: SQLite. These tables live on their own MetaData (AccountBase), separate
-- from nbastats/schema.sql -- see nbastats/accounts/models.py for why.

CREATE TABLE oauth_transactions (
	handle_hash VARCHAR(64) NOT NULL, 
	provider VARCHAR(16) NOT NULL, 
	state_hash VARCHAR(64) NOT NULL, 
	nonce VARCHAR(64) NOT NULL, 
	code_verifier VARCHAR(128) NOT NULL, 
	redirect_uri TEXT NOT NULL, 
	next_path VARCHAR(512) NOT NULL, 
	intent VARCHAR(8) NOT NULL, 
	link_user_id VARCHAR(32), 
	created_at DATETIME NOT NULL, 
	expires_at DATETIME NOT NULL, 
	consumed_at DATETIME, 
	PRIMARY KEY (handle_hash)
);

CREATE TABLE users (
	user_id VARCHAR(32) NOT NULL, 
	email VARCHAR(320), 
	email_lookup VARCHAR(320), 
	email_verified_at DATETIME, 
	is_private_relay BOOLEAN NOT NULL, 
	password_hash VARCHAR(255), 
	password_changed_at DATETIME, 
	display_name VARCHAR(128), 
	given_name VARCHAR(128), 
	family_name VARCHAR(128), 
	favorite_player_id INTEGER, 
	favorite_team_id INTEGER, 
	selected_dashboard_id VARCHAR(64), 
	theme_preference VARCHAR(8) NOT NULL, 
	profile_json TEXT NOT NULL, 
	failed_login_count INTEGER NOT NULL, 
	locked_until DATETIME, 
	is_disabled BOOLEAN NOT NULL, 
	deleted_at DATETIME, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	last_login_at DATETIME, 
	PRIMARY KEY (user_id), 
	CONSTRAINT ck_users_theme_preference CHECK (theme_preference IN ('system','light','dark')), 
	UNIQUE (email_lookup)
);

CREATE INDEX ix_users_email_lookup ON users (email_lookup);

CREATE TABLE web_invites (
	code VARCHAR(32) NOT NULL, 
	created_by VARCHAR(32), 
	used_by VARCHAR(32), 
	used_at DATETIME, 
	expires_at DATETIME, 
	note VARCHAR(120), 
	PRIMARY KEY (code)
);

CREATE TABLE auth_sessions (
	session_id VARCHAR(32) NOT NULL, 
	user_id VARCHAR(32) NOT NULL, 
	token_hash VARCHAR(64) NOT NULL, 
	csrf_hash VARCHAR(64) NOT NULL, 
	auth_method VARCHAR(16) NOT NULL, 
	created_at DATETIME NOT NULL, 
	last_seen_at DATETIME NOT NULL, 
	authenticated_at DATETIME NOT NULL, 
	idle_expires_at DATETIME NOT NULL, 
	absolute_expires_at DATETIME NOT NULL, 
	revoked_at DATETIME, 
	rotated_from VARCHAR(32), 
	user_agent VARCHAR(255), 
	ip_prefix VARCHAR(64), 
	PRIMARY KEY (session_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE, 
	UNIQUE (token_hash)
);

CREATE INDEX ix_auth_sessions_idle_expires ON auth_sessions (idle_expires_at);
CREATE INDEX ix_auth_sessions_user ON auth_sessions (user_id);

CREATE TABLE auth_tokens (
	token_id VARCHAR(32) NOT NULL, 
	user_id VARCHAR(32) NOT NULL, 
	purpose VARCHAR(16) NOT NULL, 
	token_hash VARCHAR(64) NOT NULL, 
	payload_json TEXT, 
	created_at DATETIME NOT NULL, 
	expires_at DATETIME NOT NULL, 
	consumed_at DATETIME, 
	PRIMARY KEY (token_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE, 
	UNIQUE (token_hash)
);

CREATE INDEX ix_auth_tokens_user_purpose ON auth_tokens (user_id, purpose);

CREATE TABLE user_dashboards (
	user_id VARCHAR(32) NOT NULL, 
	layout_id VARCHAR(64) NOT NULL, 
	document_json TEXT NOT NULL, 
	schema_version INTEGER NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	icon VARCHAR(64) NOT NULL, 
	accent VARCHAR(16) NOT NULL, 
	presentation VARCHAR(16) NOT NULL, 
	preset_key VARCHAR(64), 
	tagline VARCHAR(255), 
	is_preset BOOLEAN NOT NULL, 
	widget_count INTEGER NOT NULL, 
	position INTEGER NOT NULL, 
	revision INTEGER NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	PRIMARY KEY (user_id, layout_id), 
	FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX ix_dashboards_user_position ON user_dashboards (user_id, position);

CREATE TABLE user_identities (
	identity_id VARCHAR(32) NOT NULL, 
	user_id VARCHAR(32) NOT NULL, 
	provider VARCHAR(16) NOT NULL, 
	subject VARCHAR(255) NOT NULL, 
	email_at_link VARCHAR(320), 
	email_verified BOOLEAN NOT NULL, 
	created_at DATETIME NOT NULL, 
	last_login_at DATETIME, 
	PRIMARY KEY (identity_id), 
	CONSTRAINT uq_user_identities_provider_subject UNIQUE (provider, subject), 
	CONSTRAINT uq_user_identities_user_provider UNIQUE (user_id, provider), 
	FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX ix_user_identities_user ON user_identities (user_id);
