-- Hardwood NBA intel schema, generated by nbastats.nba_intel.models.render_schema_sql().
-- Do not edit by hand: run
-- `python3 -m nbastats.nba_intel.models > nbastats/nba_intel/schema.sql`.
-- Dialect: SQLite. These tables live on their own MetaData (NbaIntelBase), in the same
-- file as the stats store but never wiped by the seeder; see nba_intel/models.py.

CREATE TABLE nba_intel_job_state (
	job_key VARCHAR(64) NOT NULL, 
	last_started_at DATETIME, 
	last_success_at DATETIME, 
	last_error TEXT, 
	cursor_json TEXT, 
	PRIMARY KEY (job_key)
);

CREATE TABLE nba_intel_model_setting (
	"key" VARCHAR(48) NOT NULL, 
	value FLOAT NOT NULL, 
	provenance VARCHAR(20) NOT NULL, 
	set_at DATETIME NOT NULL, 
	PRIMARY KEY ("key"), 
	CONSTRAINT ck_nba_intel_model_setting_key CHECK (key IN ('priorRegression', 'priorWeightGames', 'leagueLevelWeight', 'homeAdvantagePoints', 'teamSd', 'marginSd', 'replacementShare', 'absorbShare', 'boostCap', 'capPolicyConsistent', 'statusChance.out', 'statusChance.doubtful', 'statusChance.questionable', 'statusChance.probable', 'statusChance.available', 'positionCoverageCeiling')), 
	CONSTRAINT ck_nba_intel_model_setting_provenance CHECK (provenance IN ('default', 'fittedPrevSeason', 'fittedLedger', 'manual'))
);

CREATE TABLE nba_intel_news_feed (
	feed_id INTEGER NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	url TEXT NOT NULL, 
	enabled BOOLEAN NOT NULL, 
	robots_checked_on DATE, 
	robots_state VARCHAR(16), 
	robots_reason VARCHAR(300), 
	etag VARCHAR(200), 
	last_modified VARCHAR(100), 
	last_fetch_at DATETIME, 
	last_status VARCHAR(40), 
	PRIMARY KEY (feed_id), 
	CONSTRAINT ck_nba_intel_news_feed_robots CHECK (robots_state IS NULL OR robots_state IN ('allowed', 'disallowed', 'unavailable')), 
	UNIQUE (url)
);

CREATE TABLE nba_intel_override (
	override_id INTEGER NOT NULL, 
	player_id INTEGER NOT NULL, 
	team_id INTEGER, 
	game_id VARCHAR(16), 
	status VARCHAR(12) NOT NULL, 
	note VARCHAR(200), 
	source_url TEXT, 
	source_published_at DATETIME, 
	created_at DATETIME NOT NULL, 
	cleared_at DATETIME, 
	entered_by_user_id VARCHAR(32), 
	PRIMARY KEY (override_id), 
	CONSTRAINT ck_nba_intel_override_status CHECK (status IN ('out', 'doubtful', 'questionable', 'probable', 'available'))
);

CREATE INDEX ix_nba_intel_override_player ON nba_intel_override (player_id);

CREATE TABLE nba_intel_raw_fetch (
	fetch_id INTEGER NOT NULL, 
	source VARCHAR(32) NOT NULL, 
	url TEXT, 
	fetched_at DATETIME NOT NULL, 
	http_status INTEGER, 
	sha256 VARCHAR(64), 
	bytes INTEGER, 
	path TEXT, 
	PRIMARY KEY (fetch_id)
);

CREATE INDEX ix_nba_intel_raw_fetch_sha ON nba_intel_raw_fetch (sha256);

CREATE TABLE nba_intel_snapshot (
	snapshot_id INTEGER NOT NULL, 
	source_kind VARCHAR(20) NOT NULL, 
	url TEXT, 
	slot_at_utc DATETIME, 
	report_as_of_utc DATETIME, 
	fetched_at DATETIME NOT NULL, 
	sha256 VARCHAR(64), 
	row_count INTEGER NOT NULL, 
	parse_status VARCHAR(16) NOT NULL, 
	parse_error TEXT, 
	PRIMARY KEY (snapshot_id), 
	CONSTRAINT ck_nba_intel_snapshot_kind CHECK (source_kind IN ('leagueReport', 'workbookImport', 'manual')), 
	CONSTRAINT ck_nba_intel_snapshot_parse CHECK (parse_status IN ('ok', 'partial', 'headerMismatch', 'empty', 'fetchFailed', 'notFound'))
);

CREATE INDEX ix_nba_intel_snapshot_sha ON nba_intel_snapshot (sha256);
CREATE INDEX ix_nba_intel_snapshot_slot ON nba_intel_snapshot (slot_at_utc);
CREATE INDEX ix_nba_intel_snapshot_url ON nba_intel_snapshot (url);

CREATE TABLE nba_intel_source_state (
	source_key VARCHAR(64) NOT NULL, 
	state VARCHAR(16) NOT NULL, 
	last_success_at DATETIME, 
	last_error TEXT, 
	consecutive_failures INTEGER NOT NULL, 
	paused_until DATETIME, 
	detail_json TEXT, 
	PRIMARY KEY (source_key), 
	CONSTRAINT ck_nba_intel_source_state_state CHECK (state IN ('ok', 'stale', 'disabled', 'notConfigured', 'noReportYet', 'blocked', 'unreadable', 'error'))
);

CREATE TABLE nba_intel_news_item (
	item_id INTEGER NOT NULL, 
	feed_id INTEGER, 
	guid VARCHAR(512), 
	title VARCHAR(300) NOT NULL, 
	link TEXT NOT NULL, 
	published_at DATETIME NOT NULL, 
	fetched_at DATETIME NOT NULL, 
	source_name VARCHAR(80) NOT NULL, 
	PRIMARY KEY (item_id), 
	CONSTRAINT uq_nba_intel_news_item_feed_guid UNIQUE (feed_id, guid), 
	FOREIGN KEY(feed_id) REFERENCES nba_intel_news_feed (feed_id)
);

CREATE INDEX ix_nba_intel_news_item_link ON nba_intel_news_item (link);
CREATE INDEX ix_nba_intel_news_item_published ON nba_intel_news_item (published_at);

CREATE TABLE nba_intel_status (
	status_id INTEGER NOT NULL, 
	team_id INTEGER NOT NULL, 
	player_id INTEGER, 
	player_name_raw VARCHAR(96) NOT NULL, 
	game_id VARCHAR(16), 
	game_date DATE, 
	status VARCHAR(12), 
	status_raw VARCHAR(40), 
	model_status VARCHAR(12), 
	reason_category VARCHAR(16), 
	reason_text VARCHAR(200), 
	expected_return_text VARCHAR(120), 
	expected_return_round_from INTEGER, 
	expected_return_round_to INTEGER, 
	expected_return_date DATE, 
	source_kind VARCHAR(20) NOT NULL, 
	source_label VARCHAR(120) NOT NULL, 
	source_url TEXT, 
	source_published_at DATETIME NOT NULL, 
	as_of DATETIME NOT NULL, 
	recorded_at DATETIME NOT NULL, 
	snapshot_id INTEGER, 
	entered_by_user_id VARCHAR(32), 
	retracts_status_id INTEGER, 
	provenance_note VARCHAR(200), 
	PRIMARY KEY (status_id), 
	CONSTRAINT ck_nba_intel_status_status CHECK (status IS NULL OR status IN ('out', 'doubtful', 'questionable', 'probable', 'available')), 
	CONSTRAINT ck_nba_intel_status_model_status CHECK (model_status IS NULL OR model_status IN ('out', 'doubtful', 'questionable', 'probable', 'available')), 
	CONSTRAINT ck_nba_intel_status_reason_category CHECK (reason_category IS NULL OR reason_category IN ('injury', 'illness', 'rest', 'coachDecision', 'personal', 'suspension', 'gLeague', 'notWithTeam', 'notRegistered', 'other')), 
	CONSTRAINT ck_nba_intel_status_kind CHECK (source_kind IN ('leagueReport', 'clubStatement', 'pressArticle', 'boxScoreInference', 'workbookImport', 'manual')), 
	CONSTRAINT ck_nba_intel_status_source_url CHECK (source_url IS NOT NULL OR source_kind = 'manual' OR source_label LIKE '%(link withheld:%'), 
	FOREIGN KEY(snapshot_id) REFERENCES nba_intel_snapshot (snapshot_id)
);

CREATE INDEX ix_nba_intel_status_player ON nba_intel_status (player_id);
CREATE INDEX ix_nba_intel_status_published ON nba_intel_status (source_published_at);
CREATE INDEX ix_nba_intel_status_snapshot ON nba_intel_status (snapshot_id);
CREATE INDEX ix_nba_intel_status_team_date ON nba_intel_status (team_id, game_date);

CREATE TABLE nba_intel_team_report (
	snapshot_id INTEGER NOT NULL, 
	team_id INTEGER NOT NULL, 
	game_id VARCHAR(16) NOT NULL, 
	state VARCHAR(16) NOT NULL, 
	PRIMARY KEY (snapshot_id, team_id, game_id), 
	CONSTRAINT ck_nba_intel_team_report_state CHECK (state IN ('submitted', 'notYetSubmitted')), 
	FOREIGN KEY(snapshot_id) REFERENCES nba_intel_snapshot (snapshot_id)
);

CREATE INDEX ix_nba_intel_team_report_team ON nba_intel_team_report (team_id);

CREATE TABLE nba_intel_news_subject (
	item_id INTEGER NOT NULL, 
	team_id INTEGER NOT NULL, 
	player_id INTEGER NOT NULL, 
	PRIMARY KEY (item_id, team_id, player_id), 
	FOREIGN KEY(item_id) REFERENCES nba_intel_news_item (item_id)
);

CREATE INDEX ix_nba_intel_news_subject_player ON nba_intel_news_subject (player_id);
CREATE INDEX ix_nba_intel_news_subject_team ON nba_intel_news_subject (team_id);
